// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	templates "gateguard/internal/pkg/notificator/templates"
)

// INotificator is an autogenerated mock type for the INotificator type
type INotificator struct {
	mock.Mock
}

type INotificator_Expecter struct {
	mock *mock.Mock
}

func (_m *INotificator) EXPECT() *INotificator_Expecter {
	return &INotificator_Expecter{mock: &_m.Mock}
}

// InviteUserToOrganization provides a mock function with given fields: ctx, to, tmpl
func (_m *INotificator) InviteUserToOrganization(ctx context.Context, to string, tmpl *templates.UserInviteToOrg) error {
	ret := _m.Called(ctx, to, tmpl)

	if len(ret) == 0 {
		panic("no return value specified for InviteUserToOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *templates.UserInviteToOrg) error); ok {
		r0 = rf(ctx, to, tmpl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// INotificator_InviteUserToOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteUserToOrganization'
type INotificator_InviteUserToOrganization_Call struct {
	*mock.Call
}

// InviteUserToOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - tmpl *templates.UserInviteToOrg
func (_e *INotificator_Expecter) InviteUserToOrganization(ctx interface{}, to interface{}, tmpl interface{}) *INotificator_InviteUserToOrganization_Call {
	return &INotificator_InviteUserToOrganization_Call{Call: _e.mock.On("InviteUserToOrganization", ctx, to, tmpl)}
}

func (_c *INotificator_InviteUserToOrganization_Call) Run(run func(ctx context.Context, to string, tmpl *templates.UserInviteToOrg)) *INotificator_InviteUserToOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*templates.UserInviteToOrg))
	})
	return _c
}

func (_c *INotificator_InviteUserToOrganization_Call) Return(_a0 error) *INotificator_InviteUserToOrganization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *INotificator_InviteUserToOrganization_Call) RunAndReturn(run func(context.Context, string, *templates.UserInviteToOrg) error) *INotificator_InviteUserToOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// SendEmailVerification provides a mock function with given fields: ctx, to, code
func (_m *INotificator) SendEmailVerification(ctx context.Context, to string, code string) error {
	ret := _m.Called(ctx, to, code)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailVerification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, to, code)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// INotificator_SendEmailVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEmailVerification'
type INotificator_SendEmailVerification_Call struct {
	*mock.Call
}

// SendEmailVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - code string
func (_e *INotificator_Expecter) SendEmailVerification(ctx interface{}, to interface{}, code interface{}) *INotificator_SendEmailVerification_Call {
	return &INotificator_SendEmailVerification_Call{Call: _e.mock.On("SendEmailVerification", ctx, to, code)}
}

func (_c *INotificator_SendEmailVerification_Call) Run(run func(ctx context.Context, to string, code string)) *INotificator_SendEmailVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *INotificator_SendEmailVerification_Call) Return(_a0 error) *INotificator_SendEmailVerification_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *INotificator_SendEmailVerification_Call) RunAndReturn(run func(context.Context, string, string) error) *INotificator_SendEmailVerification_Call {
	_c.Call.Return(run)
	return _c
}

// NewINotificator creates a new instance of INotificator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewINotificator(t interface {
	mock.TestingT
	Cleanup(func())
}) *INotificator {
	mock := &INotificator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
