// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LinkBuilder is an autogenerated mock type for the LinkBuilder type
type LinkBuilder struct {
	mock.Mock
}

type LinkBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkBuilder) EXPECT() *LinkBuilder_Expecter {
	return &LinkBuilder_Expecter{mock: &_m.Mock}
}

// GetReferralLink provides a mock function with given fields: refCode
func (_m *LinkBuilder) GetReferralLink(refCode string) string {
	ret := _m.Called(refCode)

	if len(ret) == 0 {
		panic("no return value specified for GetReferralLink")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(refCode)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// LinkBuilder_GetReferralLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReferralLink'
type LinkBuilder_GetReferralLink_Call struct {
	*mock.Call
}

// GetReferralLink is a helper method to define mock.On call
//   - refCode string
func (_e *LinkBuilder_Expecter) GetReferralLink(refCode interface{}) *LinkBuilder_GetReferralLink_Call {
	return &LinkBuilder_GetReferralLink_Call{Call: _e.mock.On("GetReferralLink", refCode)}
}

func (_c *LinkBuilder_GetReferralLink_Call) Run(run func(refCode string)) *LinkBuilder_GetReferralLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *LinkBuilder_GetReferralLink_Call) Return(_a0 string) *LinkBuilder_GetReferralLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkBuilder_GetReferralLink_Call) RunAndReturn(run func(string) string) *LinkBuilder_GetReferralLink_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkBuilder creates a new instance of LinkBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkBuilder {
	mock := &LinkBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
