// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ITemplate is an autogenerated mock type for the ITemplate type
type ITemplate struct {
	mock.Mock
}

type ITemplate_Expecter struct {
	mock *mock.Mock
}

func (_m *ITemplate) EXPECT() *ITemplate_Expecter {
	return &ITemplate_Expecter{mock: &_m.Mock}
}

// GetTemplateAsString provides a mock function with given fields: ctx
func (_m *ITemplate) GetTemplateAsString(ctx context.Context) (string, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTemplateAsString")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (string, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ITemplate_GetTemplateAsString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTemplateAsString'
type ITemplate_GetTemplateAsString_Call struct {
	*mock.Call
}

// GetTemplateAsString is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ITemplate_Expecter) GetTemplateAsString(ctx interface{}) *ITemplate_GetTemplateAsString_Call {
	return &ITemplate_GetTemplateAsString_Call{Call: _e.mock.On("GetTemplateAsString", ctx)}
}

func (_c *ITemplate_GetTemplateAsString_Call) Run(run func(ctx context.Context)) *ITemplate_GetTemplateAsString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ITemplate_GetTemplateAsString_Call) Return(_a0 string, _a1 error) *ITemplate_GetTemplateAsString_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ITemplate_GetTemplateAsString_Call) RunAndReturn(run func(context.Context) (string, error)) *ITemplate_GetTemplateAsString_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function with given fields:
func (_m *ITemplate) Subject() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ITemplate_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type ITemplate_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *ITemplate_Expecter) Subject() *ITemplate_Subject_Call {
	return &ITemplate_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *ITemplate_Subject_Call) Run(run func()) *ITemplate_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ITemplate_Subject_Call) Return(_a0 string) *ITemplate_Subject_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ITemplate_Subject_Call) RunAndReturn(run func() string) *ITemplate_Subject_Call {
	_c.Call.Return(run)
	return _c
}

// TemplateName provides a mock function with given fields:
func (_m *ITemplate) TemplateName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TemplateName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ITemplate_TemplateName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TemplateName'
type ITemplate_TemplateName_Call struct {
	*mock.Call
}

// TemplateName is a helper method to define mock.On call
func (_e *ITemplate_Expecter) TemplateName() *ITemplate_TemplateName_Call {
	return &ITemplate_TemplateName_Call{Call: _e.mock.On("TemplateName")}
}

func (_c *ITemplate_TemplateName_Call) Run(run func()) *ITemplate_TemplateName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ITemplate_TemplateName_Call) Return(_a0 string) *ITemplate_TemplateName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ITemplate_TemplateName_Call) RunAndReturn(run func() string) *ITemplate_TemplateName_Call {
	_c.Call.Return(run)
	return _c
}

// NewITemplate creates a new instance of ITemplate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewITemplate(t interface {
	mock.TestingT
	Cleanup(func())
}) *ITemplate {
	mock := &ITemplate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
