// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"github.com/andskur/gatekeeper"

	mock "github.com/stretchr/testify/mock"
)

// ISessions is an autogenerated mock type for the ISessions type
type ISessions struct {
	mock.Mock
}

type ISessions_Expecter struct {
	mock *mock.Mock
}

func (_m *ISessions) EXPECT() *ISessions_Expecter {
	return &ISessions_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: data
func (_m *ISessions) Create(data map[string]interface{}) (sessions.Token, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 sessions.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]interface{}) (sessions.Token, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func(map[string]interface{}) sessions.Token); ok {
		r0 = rf(data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sessions.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]interface{}) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISessions_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type ISessions_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - data map[string]interface{}
func (_e *ISessions_Expecter) Create(data interface{}) *ISessions_Create_Call {
	return &ISessions_Create_Call{Call: _e.mock.On("Create", data)}
}

func (_c *ISessions_Create_Call) Run(run func(data map[string]interface{})) *ISessions_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]interface{}))
	})
	return _c
}

func (_c *ISessions_Create_Call) Return(_a0 sessions.Token, _a1 error) *ISessions_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISessions_Create_Call) RunAndReturn(run func(map[string]interface{}) (sessions.Token, error)) *ISessions_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: token
func (_m *ISessions) Delete(token sessions.Token) error {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(sessions.Token) error); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ISessions_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type ISessions_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - token sessions.Token
func (_e *ISessions_Expecter) Delete(token interface{}) *ISessions_Delete_Call {
	return &ISessions_Delete_Call{Call: _e.mock.On("Delete", token)}
}

func (_c *ISessions_Delete_Call) Run(run func(token sessions.Token)) *ISessions_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(sessions.Token))
	})
	return _c
}

func (_c *ISessions_Delete_Call) Return(_a0 error) *ISessions_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ISessions_Delete_Call) RunAndReturn(run func(sessions.Token) error) *ISessions_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: token
func (_m *ISessions) Get(token sessions.Token) (map[string]interface{}, error) {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(sessions.Token) (map[string]interface{}, error)); ok {
		return rf(token)
	}
	if rf, ok := ret.Get(0).(func(sessions.Token) map[string]interface{}); ok {
		r0 = rf(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(sessions.Token) error); ok {
		r1 = rf(token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISessions_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type ISessions_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - token sessions.Token
func (_e *ISessions_Expecter) Get(token interface{}) *ISessions_Get_Call {
	return &ISessions_Get_Call{Call: _e.mock.On("Get", token)}
}

func (_c *ISessions_Get_Call) Run(run func(token sessions.Token)) *ISessions_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(sessions.Token))
	})
	return _c
}

func (_c *ISessions_Get_Call) Return(data map[string]interface{}, err error) *ISessions_Get_Call {
	_c.Call.Return(data, err)
	return _c
}

func (_c *ISessions_Get_Call) RunAndReturn(run func(sessions.Token) (map[string]interface{}, error)) *ISessions_Get_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshToken provides a mock function with given fields: oldToken
func (_m *ISessions) RefreshToken(oldToken sessions.Token) (sessions.Token, error) {
	ret := _m.Called(oldToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 sessions.Token
	var r1 error
	if rf, ok := ret.Get(0).(func(sessions.Token) (sessions.Token, error)); ok {
		return rf(oldToken)
	}
	if rf, ok := ret.Get(0).(func(sessions.Token) sessions.Token); ok {
		r0 = rf(oldToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(sessions.Token)
		}
	}

	if rf, ok := ret.Get(1).(func(sessions.Token) error); ok {
		r1 = rf(oldToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ISessions_RefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshToken'
type ISessions_RefreshToken_Call struct {
	*mock.Call
}

// RefreshToken is a helper method to define mock.On call
//   - oldToken sessions.Token
func (_e *ISessions_Expecter) RefreshToken(oldToken interface{}) *ISessions_RefreshToken_Call {
	return &ISessions_RefreshToken_Call{Call: _e.mock.On("RefreshToken", oldToken)}
}

func (_c *ISessions_RefreshToken_Call) Run(run func(oldToken sessions.Token)) *ISessions_RefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(sessions.Token))
	})
	return _c
}

func (_c *ISessions_RefreshToken_Call) Return(_a0 sessions.Token, _a1 error) *ISessions_RefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ISessions_RefreshToken_Call) RunAndReturn(run func(sessions.Token) (sessions.Token, error)) *ISessions_RefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewISessions creates a new instance of ISessions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewISessions(t interface {
	mock.TestingT
	Cleanup(func())
}) *ISessions {
	mock := &ISessions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
