// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "gateguard/internal/models"

	mock "github.com/stretchr/testify/mock"

	service "gateguard/internal/service"

	sessions "github.com/andskur/gatekeeper"

	uuid "github.com/gofrs/uuid"
)

// IUsersService is an autogenerated mock type for the IUsersService type
type IUsersService struct {
	mock.Mock
}

type IUsersService_Expecter struct {
	mock *mock.Mock
}

func (_m *IUsersService) EXPECT() *IUsersService_Expecter {
	return &IUsersService_Expecter{mock: &_m.Mock}
}

// AddOrganizationToUser provides a mock function with given fields: ctx, userUUID, organizationUUID
func (_m *IUsersService) AddOrganizationToUser(ctx context.Context, userUUID uuid.UUID, organizationUUID uuid.UUID) error {
	ret := _m.Called(ctx, userUUID, organizationUUID)

	if len(ret) == 0 {
		panic("no return value specified for AddOrganizationToUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userUUID, organizationUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersService_AddOrganizationToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddOrganizationToUser'
type IUsersService_AddOrganizationToUser_Call struct {
	*mock.Call
}

// AddOrganizationToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
//   - organizationUUID uuid.UUID
func (_e *IUsersService_Expecter) AddOrganizationToUser(ctx interface{}, userUUID interface{}, organizationUUID interface{}) *IUsersService_AddOrganizationToUser_Call {
	return &IUsersService_AddOrganizationToUser_Call{Call: _e.mock.On("AddOrganizationToUser", ctx, userUUID, organizationUUID)}
}

func (_c *IUsersService_AddOrganizationToUser_Call) Run(run func(ctx context.Context, userUUID uuid.UUID, organizationUUID uuid.UUID)) *IUsersService_AddOrganizationToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *IUsersService_AddOrganizationToUser_Call) Return(_a0 error) *IUsersService_AddOrganizationToUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersService_AddOrganizationToUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *IUsersService_AddOrganizationToUser_Call {
	_c.Call.Return(run)
	return _c
}

// AllInvitations provides a mock function with given fields: ctx, filter
func (_m *IUsersService) AllInvitations(ctx context.Context, filter *service.AllInvitationsFilter) ([]*models.Invitation, bool, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for AllInvitations")
	}

	var r0 []*models.Invitation
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.AllInvitationsFilter) ([]*models.Invitation, bool, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *service.AllInvitationsFilter) []*models.Invitation); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *service.AllInvitationsFilter) bool); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *service.AllInvitationsFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IUsersService_AllInvitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllInvitations'
type IUsersService_AllInvitations_Call struct {
	*mock.Call
}

// AllInvitations is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *service.AllInvitationsFilter
func (_e *IUsersService_Expecter) AllInvitations(ctx interface{}, filter interface{}) *IUsersService_AllInvitations_Call {
	return &IUsersService_AllInvitations_Call{Call: _e.mock.On("AllInvitations", ctx, filter)}
}

func (_c *IUsersService_AllInvitations_Call) Run(run func(ctx context.Context, filter *service.AllInvitationsFilter)) *IUsersService_AllInvitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*service.AllInvitationsFilter))
	})
	return _c
}

func (_c *IUsersService_AllInvitations_Call) Return(_a0 []*models.Invitation, _a1 bool, _a2 error) *IUsersService_AllInvitations_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IUsersService_AllInvitations_Call) RunAndReturn(run func(context.Context, *service.AllInvitationsFilter) ([]*models.Invitation, bool, error)) *IUsersService_AllInvitations_Call {
	_c.Call.Return(run)
	return _c
}

// AllUsers provides a mock function with given fields: ctx
func (_m *IUsersService) AllUsers(ctx context.Context) ([]*models.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllUsers")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUsersService_AllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllUsers'
type IUsersService_AllUsers_Call struct {
	*mock.Call
}

// AllUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IUsersService_Expecter) AllUsers(ctx interface{}) *IUsersService_AllUsers_Call {
	return &IUsersService_AllUsers_Call{Call: _e.mock.On("AllUsers", ctx)}
}

func (_c *IUsersService_AllUsers_Call) Run(run func(ctx context.Context)) *IUsersService_AllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IUsersService_AllUsers_Call) Return(_a0 []*models.User, _a1 error) *IUsersService_AllUsers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUsersService_AllUsers_Call) RunAndReturn(run func(context.Context) ([]*models.User, error)) *IUsersService_AllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// CheckAuth provides a mock function with given fields: ctx, token
func (_m *IUsersService) CheckAuth(ctx context.Context, token []byte) (*models.User, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for CheckAuth")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) (*models.User, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte) *models.User); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUsersService_CheckAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckAuth'
type IUsersService_CheckAuth_Call struct {
	*mock.Call
}

// CheckAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - token []byte
func (_e *IUsersService_Expecter) CheckAuth(ctx interface{}, token interface{}) *IUsersService_CheckAuth_Call {
	return &IUsersService_CheckAuth_Call{Call: _e.mock.On("CheckAuth", ctx, token)}
}

func (_c *IUsersService_CheckAuth_Call) Run(run func(ctx context.Context, token []byte)) *IUsersService_CheckAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *IUsersService_CheckAuth_Call) Return(_a0 *models.User, _a1 error) *IUsersService_CheckAuth_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUsersService_CheckAuth_Call) RunAndReturn(run func(context.Context, []byte) (*models.User, error)) *IUsersService_CheckAuth_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function with given fields: ctx, token
func (_m *IUsersService) DeleteUser(ctx context.Context, token []byte) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type IUsersService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - token []byte
func (_e *IUsersService_Expecter) DeleteUser(ctx interface{}, token interface{}) *IUsersService_DeleteUser_Call {
	return &IUsersService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, token)}
}

func (_c *IUsersService_DeleteUser_Call) Run(run func(ctx context.Context, token []byte)) *IUsersService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *IUsersService_DeleteUser_Call) Return(_a0 error) *IUsersService_DeleteUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersService_DeleteUser_Call) RunAndReturn(run func(context.Context, []byte) error) *IUsersService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ExpireInvitations provides a mock function with given fields: ctx
func (_m *IUsersService) ExpireInvitations(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ExpireInvitations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersService_ExpireInvitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpireInvitations'
type IUsersService_ExpireInvitations_Call struct {
	*mock.Call
}

// ExpireInvitations is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IUsersService_Expecter) ExpireInvitations(ctx interface{}) *IUsersService_ExpireInvitations_Call {
	return &IUsersService_ExpireInvitations_Call{Call: _e.mock.On("ExpireInvitations", ctx)}
}

func (_c *IUsersService_ExpireInvitations_Call) Run(run func(ctx context.Context)) *IUsersService_ExpireInvitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IUsersService_ExpireInvitations_Call) Return(_a0 error) *IUsersService_ExpireInvitations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersService_ExpireInvitations_Call) RunAndReturn(run func(context.Context) error) *IUsersService_ExpireInvitations_Call {
	_c.Call.Return(run)
	return _c
}

// InviteUserByEmail provides a mock function with given fields: ctx, in
func (_m *IUsersService) InviteUserByEmail(ctx context.Context, in service.InviteUserByEmailIn) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for InviteUserByEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.InviteUserByEmailIn) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersService_InviteUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InviteUserByEmail'
type IUsersService_InviteUserByEmail_Call struct {
	*mock.Call
}

// InviteUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - in service.InviteUserByEmailIn
func (_e *IUsersService_Expecter) InviteUserByEmail(ctx interface{}, in interface{}) *IUsersService_InviteUserByEmail_Call {
	return &IUsersService_InviteUserByEmail_Call{Call: _e.mock.On("InviteUserByEmail", ctx, in)}
}

func (_c *IUsersService_InviteUserByEmail_Call) Run(run func(ctx context.Context, in service.InviteUserByEmailIn)) *IUsersService_InviteUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.InviteUserByEmailIn))
	})
	return _c
}

func (_c *IUsersService_InviteUserByEmail_Call) Return(_a0 error) *IUsersService_InviteUserByEmail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersService_InviteUserByEmail_Call) RunAndReturn(run func(context.Context, service.InviteUserByEmailIn) error) *IUsersService_InviteUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// ReactToInvitation provides a mock function with given fields: ctx, in
func (_m *IUsersService) ReactToInvitation(ctx context.Context, in service.ReactToInvitationIn) error {
	ret := _m.Called(ctx, in)

	if len(ret) == 0 {
		panic("no return value specified for ReactToInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, service.ReactToInvitationIn) error); ok {
		r0 = rf(ctx, in)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersService_ReactToInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReactToInvitation'
type IUsersService_ReactToInvitation_Call struct {
	*mock.Call
}

// ReactToInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - in service.ReactToInvitationIn
func (_e *IUsersService_Expecter) ReactToInvitation(ctx interface{}, in interface{}) *IUsersService_ReactToInvitation_Call {
	return &IUsersService_ReactToInvitation_Call{Call: _e.mock.On("ReactToInvitation", ctx, in)}
}

func (_c *IUsersService_ReactToInvitation_Call) Run(run func(ctx context.Context, in service.ReactToInvitationIn)) *IUsersService_ReactToInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.ReactToInvitationIn))
	})
	return _c
}

func (_c *IUsersService_ReactToInvitation_Call) Return(_a0 error) *IUsersService_ReactToInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersService_ReactToInvitation_Call) RunAndReturn(run func(context.Context, service.ReactToInvitationIn) error) *IUsersService_ReactToInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveOrganizationFromUser provides a mock function with given fields: ctx, userUUID, organizationUUID
func (_m *IUsersService) RemoveOrganizationFromUser(ctx context.Context, userUUID uuid.UUID, organizationUUID uuid.UUID) error {
	ret := _m.Called(ctx, userUUID, organizationUUID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveOrganizationFromUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, userUUID, organizationUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersService_RemoveOrganizationFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveOrganizationFromUser'
type IUsersService_RemoveOrganizationFromUser_Call struct {
	*mock.Call
}

// RemoveOrganizationFromUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
//   - organizationUUID uuid.UUID
func (_e *IUsersService_Expecter) RemoveOrganizationFromUser(ctx interface{}, userUUID interface{}, organizationUUID interface{}) *IUsersService_RemoveOrganizationFromUser_Call {
	return &IUsersService_RemoveOrganizationFromUser_Call{Call: _e.mock.On("RemoveOrganizationFromUser", ctx, userUUID, organizationUUID)}
}

func (_c *IUsersService_RemoveOrganizationFromUser_Call) Run(run func(ctx context.Context, userUUID uuid.UUID, organizationUUID uuid.UUID)) *IUsersService_RemoveOrganizationFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *IUsersService_RemoveOrganizationFromUser_Call) Return(_a0 error) *IUsersService_RemoveOrganizationFromUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersService_RemoveOrganizationFromUser_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *IUsersService_RemoveOrganizationFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetUsersPreferredStack provides a mock function with given fields: ctx, userUUID, stacks
func (_m *IUsersService) SetUsersPreferredStack(ctx context.Context, userUUID uuid.UUID, stacks []int64) error {
	ret := _m.Called(ctx, userUUID, stacks)

	if len(ret) == 0 {
		panic("no return value specified for SetUsersPreferredStack")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []int64) error); ok {
		r0 = rf(ctx, userUUID, stacks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersService_SetUsersPreferredStack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUsersPreferredStack'
type IUsersService_SetUsersPreferredStack_Call struct {
	*mock.Call
}

// SetUsersPreferredStack is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
//   - stacks []int64
func (_e *IUsersService_Expecter) SetUsersPreferredStack(ctx interface{}, userUUID interface{}, stacks interface{}) *IUsersService_SetUsersPreferredStack_Call {
	return &IUsersService_SetUsersPreferredStack_Call{Call: _e.mock.On("SetUsersPreferredStack", ctx, userUUID, stacks)}
}

func (_c *IUsersService_SetUsersPreferredStack_Call) Run(run func(ctx context.Context, userUUID uuid.UUID, stacks []int64)) *IUsersService_SetUsersPreferredStack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]int64))
	})
	return _c
}

func (_c *IUsersService_SetUsersPreferredStack_Call) Return(_a0 error) *IUsersService_SetUsersPreferredStack_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersService_SetUsersPreferredStack_Call) RunAndReturn(run func(context.Context, uuid.UUID, []int64) error) *IUsersService_SetUsersPreferredStack_Call {
	_c.Call.Return(run)
	return _c
}

// SetUsersTrialUsed provides a mock function with given fields: ctx, userUUID, trialUsed
func (_m *IUsersService) SetUsersTrialUsed(ctx context.Context, userUUID uuid.UUID, trialUsed bool) error {
	ret := _m.Called(ctx, userUUID, trialUsed)

	if len(ret) == 0 {
		panic("no return value specified for SetUsersTrialUsed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, bool) error); ok {
		r0 = rf(ctx, userUUID, trialUsed)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersService_SetUsersTrialUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUsersTrialUsed'
type IUsersService_SetUsersTrialUsed_Call struct {
	*mock.Call
}

// SetUsersTrialUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
//   - trialUsed bool
func (_e *IUsersService_Expecter) SetUsersTrialUsed(ctx interface{}, userUUID interface{}, trialUsed interface{}) *IUsersService_SetUsersTrialUsed_Call {
	return &IUsersService_SetUsersTrialUsed_Call{Call: _e.mock.On("SetUsersTrialUsed", ctx, userUUID, trialUsed)}
}

func (_c *IUsersService_SetUsersTrialUsed_Call) Run(run func(ctx context.Context, userUUID uuid.UUID, trialUsed bool)) *IUsersService_SetUsersTrialUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(bool))
	})
	return _c
}

func (_c *IUsersService_SetUsersTrialUsed_Call) Return(_a0 error) *IUsersService_SetUsersTrialUsed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersService_SetUsersTrialUsed_Call) RunAndReturn(run func(context.Context, uuid.UUID, bool) error) *IUsersService_SetUsersTrialUsed_Call {
	_c.Call.Return(run)
	return _c
}

// SignInOAuth provides a mock function with given fields: ctx, user
func (_m *IUsersService) SignInOAuth(ctx context.Context, user *models.User) ([]byte, *models.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SignInOAuth")
	}

	var r0 []byte
	var r1 *models.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) ([]byte, *models.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) []byte); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *models.User) *models.User); ok {
		r1 = rf(ctx, user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*models.User)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *models.User) error); ok {
		r2 = rf(ctx, user)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IUsersService_SignInOAuth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignInOAuth'
type IUsersService_SignInOAuth_Call struct {
	*mock.Call
}

// SignInOAuth is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *IUsersService_Expecter) SignInOAuth(ctx interface{}, user interface{}) *IUsersService_SignInOAuth_Call {
	return &IUsersService_SignInOAuth_Call{Call: _e.mock.On("SignInOAuth", ctx, user)}
}

func (_c *IUsersService_SignInOAuth_Call) Run(run func(ctx context.Context, user *models.User)) *IUsersService_SignInOAuth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *IUsersService_SignInOAuth_Call) Return(_a0 []byte, _a1 *models.User, _a2 error) *IUsersService_SignInOAuth_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IUsersService_SignInOAuth_Call) RunAndReturn(run func(context.Context, *models.User) ([]byte, *models.User, error)) *IUsersService_SignInOAuth_Call {
	_c.Call.Return(run)
	return _c
}

// SignOut provides a mock function with given fields: ctx, token
func (_m *IUsersService) SignOut(ctx context.Context, token []byte) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SignOut")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersService_SignOut_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignOut'
type IUsersService_SignOut_Call struct {
	*mock.Call
}

// SignOut is a helper method to define mock.On call
//   - ctx context.Context
//   - token []byte
func (_e *IUsersService_Expecter) SignOut(ctx interface{}, token interface{}) *IUsersService_SignOut_Call {
	return &IUsersService_SignOut_Call{Call: _e.mock.On("SignOut", ctx, token)}
}

func (_c *IUsersService_SignOut_Call) Run(run func(ctx context.Context, token []byte)) *IUsersService_SignOut_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte))
	})
	return _c
}

func (_c *IUsersService_SignOut_Call) Return(_a0 error) *IUsersService_SignOut_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersService_SignOut_Call) RunAndReturn(run func(context.Context, []byte) error) *IUsersService_SignOut_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function with given fields: ctx, userUUID, role
func (_m *IUsersService) UpdateRole(ctx context.Context, userUUID uuid.UUID, role models.UserRole) error {
	ret := _m.Called(ctx, userUUID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, models.UserRole) error); ok {
		r0 = rf(ctx, userUUID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IUsersService_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type IUsersService_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
//   - role models.UserRole
func (_e *IUsersService_Expecter) UpdateRole(ctx interface{}, userUUID interface{}, role interface{}) *IUsersService_UpdateRole_Call {
	return &IUsersService_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, userUUID, role)}
}

func (_c *IUsersService_UpdateRole_Call) Run(run func(ctx context.Context, userUUID uuid.UUID, role models.UserRole)) *IUsersService_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(models.UserRole))
	})
	return _c
}

func (_c *IUsersService_UpdateRole_Call) Return(_a0 error) *IUsersService_UpdateRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IUsersService_UpdateRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, models.UserRole) error) *IUsersService_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// UserByEmail provides a mock function with given fields: ctx, email
func (_m *IUsersService) UserByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for UserByEmail")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUsersService_UserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByEmail'
type IUsersService_UserByEmail_Call struct {
	*mock.Call
}

// UserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *IUsersService_Expecter) UserByEmail(ctx interface{}, email interface{}) *IUsersService_UserByEmail_Call {
	return &IUsersService_UserByEmail_Call{Call: _e.mock.On("UserByEmail", ctx, email)}
}

func (_c *IUsersService_UserByEmail_Call) Run(run func(ctx context.Context, email string)) *IUsersService_UserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *IUsersService_UserByEmail_Call) Return(_a0 *models.User, _a1 error) *IUsersService_UserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUsersService_UserByEmail_Call) RunAndReturn(run func(context.Context, string) (*models.User, error)) *IUsersService_UserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// UserByUUID provides a mock function with given fields: ctx, userUUID
func (_m *IUsersService) UserByUUID(ctx context.Context, userUUID uuid.UUID) (*models.User, error) {
	ret := _m.Called(ctx, userUUID)

	if len(ret) == 0 {
		panic("no return value specified for UserByUUID")
	}

	var r0 *models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return rf(ctx, userUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = rf(ctx, userUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IUsersService_UserByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserByUUID'
type IUsersService_UserByUUID_Call struct {
	*mock.Call
}

// UserByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - userUUID uuid.UUID
func (_e *IUsersService_Expecter) UserByUUID(ctx interface{}, userUUID interface{}) *IUsersService_UserByUUID_Call {
	return &IUsersService_UserByUUID_Call{Call: _e.mock.On("UserByUUID", ctx, userUUID)}
}

func (_c *IUsersService_UserByUUID_Call) Run(run func(ctx context.Context, userUUID uuid.UUID)) *IUsersService_UserByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *IUsersService_UserByUUID_Call) Return(_a0 *models.User, _a1 error) *IUsersService_UserByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IUsersService_UserByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.User, error)) *IUsersService_UserByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// --- Hand-added to match interface methods (mockery unavailable on this Go toolchain). ---

// SignUpWithPassword provides a mock function with given fields: ctx, email, name, plain
func (_m *IUsersService) SignUpWithPassword(ctx context.Context, email string, name string, plain string) ([]byte, *models.User, error) {
	ret := _m.Called(ctx, email, name, plain)

	if len(ret) == 0 {
		panic("no return value specified for SignUpWithPassword")
	}

	var r0 []byte
	var r1 *models.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) ([]byte, *models.User, error)); ok {
		return rf(ctx, email, name, plain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) []byte); ok {
		r0 = rf(ctx, email, name, plain)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]byte)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) *models.User); ok {
		r1 = rf(ctx, email, name, plain)
	} else if ret.Get(1) != nil {
		r1 = ret.Get(1).(*models.User)
	}
	if rf, ok := ret.Get(2).(func(context.Context, string, string, string) error); ok {
		r2 = rf(ctx, email, name, plain)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SignInWithPassword provides a mock function with given fields: ctx, email, plain
func (_m *IUsersService) SignInWithPassword(ctx context.Context, email string, plain string) ([]byte, *models.User, error) {
	ret := _m.Called(ctx, email, plain)

	if len(ret) == 0 {
		panic("no return value specified for SignInWithPassword")
	}

	var r0 []byte
	var r1 *models.User
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]byte, *models.User, error)); ok {
		return rf(ctx, email, plain)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []byte); ok {
		r0 = rf(ctx, email, plain)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).([]byte)
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, string) *models.User); ok {
		r1 = rf(ctx, email, plain)
	} else if ret.Get(1) != nil {
		r1 = ret.Get(1).(*models.User)
	}
	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, email, plain)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// RequestEmailVerification provides a mock function with given fields: ctx, email
func (_m *IUsersService) RequestEmailVerification(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for RequestEmailVerification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MarkEmailVerified provides a mock function with given fields: ctx, email
func (_m *IUsersService) MarkEmailVerified(ctx context.Context, email string) error {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for MarkEmailVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyEmail provides a mock function with given fields: ctx, email, token
func (_m *IUsersService) VerifyEmail(ctx context.Context, email string, token string) error {
	ret := _m.Called(ctx, email, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, email, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetExtendedSession provides a mock function with given fields: extendedSession
func (_m *IUsersService) SetExtendedSession(extendedSession sessions.ISessions) {
	_m.Called(extendedSession)
}

// NewIUsersService creates a new instance of IUsersService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIUsersService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IUsersService {
	mock := &IUsersService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
