// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: models_gateguard.proto

package gateguard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserStatus is enum with available User statuses
type UserStatus int32

const (
	// Unknown status
	UserStatus_UserUnknown UserStatus = 0
	// Active user with all access to API
	UserStatus_UserActive UserStatus = 2
	// Archived user with no access to API
	UserStatus_UserArchive UserStatus = 3
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "UserUnknown",
		2: "UserActive",
		3: "UserArchive",
	}
	UserStatus_value = map[string]int32{
		"UserUnknown": 0,
		"UserActive":  2,
		"UserArchive": 3,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_models_gateguard_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_models_gateguard_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_models_gateguard_proto_rawDescGZIP(), []int{0}
}

type UserRole int32

const (
	UserRole_UserRoleUnknown UserRole = 0
	UserRole_UserRoleCommon  UserRole = 1
	UserRole_UserRoleViewer  UserRole = 2
	UserRole_UserRoleBilling UserRole = 3
	UserRole_UserRoleAdmin   UserRole = 4
)

// Enum value maps for UserRole.
var (
	UserRole_name = map[int32]string{
		0: "UserRoleUnknown",
		1: "UserRoleCommon",
		2: "UserRoleViewer",
		3: "UserRoleBilling",
		4: "UserRoleAdmin",
	}
	UserRole_value = map[string]int32{
		"UserRoleUnknown": 0,
		"UserRoleCommon":  1,
		"UserRoleViewer":  2,
		"UserRoleBilling": 3,
		"UserRoleAdmin":   4,
	}
)

func (x UserRole) Enum() *UserRole {
	p := new(UserRole)
	*p = x
	return p
}

func (x UserRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserRole) Descriptor() protoreflect.EnumDescriptor {
	return file_models_gateguard_proto_enumTypes[1].Descriptor()
}

func (UserRole) Type() protoreflect.EnumType {
	return &file_models_gateguard_proto_enumTypes[1]
}

func (x UserRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserRole.Descriptor instead.
func (UserRole) EnumDescriptor() ([]byte, []int) {
	return file_models_gateguard_proto_rawDescGZIP(), []int{1}
}

type RoleType int32

const (
	RoleType_RoleUnknown RoleType = 0
	RoleType_RoleOwner   RoleType = 1
	RoleType_RoleBilling RoleType = 2
	RoleType_RoleCreator RoleType = 3
	RoleType_RoleCommon  RoleType = 4
)

// Enum value maps for RoleType.
var (
	RoleType_name = map[int32]string{
		0: "RoleUnknown",
		1: "RoleOwner",
		2: "RoleBilling",
		3: "RoleCreator",
		4: "RoleCommon",
	}
	RoleType_value = map[string]int32{
		"RoleUnknown": 0,
		"RoleOwner":   1,
		"RoleBilling": 2,
		"RoleCreator": 3,
		"RoleCommon":  4,
	}
)

func (x RoleType) Enum() *RoleType {
	p := new(RoleType)
	*p = x
	return p
}

func (x RoleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoleType) Descriptor() protoreflect.EnumDescriptor {
	return file_models_gateguard_proto_enumTypes[2].Descriptor()
}

func (RoleType) Type() protoreflect.EnumType {
	return &file_models_gateguard_proto_enumTypes[2]
}

func (x RoleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoleType.Descriptor instead.
func (RoleType) EnumDescriptor() ([]byte, []int) {
	return file_models_gateguard_proto_rawDescGZIP(), []int{2}
}

type InvitationStatus int32

const (
	InvitationStatus_InvitationPending  InvitationStatus = 0
	InvitationStatus_InvitationAccepted InvitationStatus = 1
	InvitationStatus_InvitationDeclined InvitationStatus = 2
	InvitationStatus_InvitationIgnored  InvitationStatus = 3
	InvitationStatus_InvitationRevoked  InvitationStatus = 4
	InvitationStatus_InvitationUnknown  InvitationStatus = 5
)

// Enum value maps for InvitationStatus.
var (
	InvitationStatus_name = map[int32]string{
		0: "InvitationPending",
		1: "InvitationAccepted",
		2: "InvitationDeclined",
		3: "InvitationIgnored",
		4: "InvitationRevoked",
		5: "InvitationUnknown",
	}
	InvitationStatus_value = map[string]int32{
		"InvitationPending":  0,
		"InvitationAccepted": 1,
		"InvitationDeclined": 2,
		"InvitationIgnored":  3,
		"InvitationRevoked":  4,
		"InvitationUnknown":  5,
	}
)

func (x InvitationStatus) Enum() *InvitationStatus {
	p := new(InvitationStatus)
	*p = x
	return p
}

func (x InvitationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvitationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_models_gateguard_proto_enumTypes[3].Descriptor()
}

func (InvitationStatus) Type() protoreflect.EnumType {
	return &file_models_gateguard_proto_enumTypes[3]
}

func (x InvitationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvitationStatus.Descriptor instead.
func (InvitationStatus) EnumDescriptor() ([]byte, []int) {
	return file_models_gateguard_proto_rawDescGZIP(), []int{3}
}

// User is
type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uuid            []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name            string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar          string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status          UserStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=gateguard.models.UserStatus" json:"status,omitempty"`
	Created         int64                  `protobuf:"varint,6,opt,name=created,proto3" json:"created,omitempty"`
	Ip              uint32                 `protobuf:"varint,7,opt,name=ip,proto3" json:"ip,omitempty"`
	RefCode         string                 `protobuf:"bytes,8,opt,name=refCode,proto3" json:"refCode,omitempty"`
	Role            UserRole               `protobuf:"varint,9,opt,name=role,proto3,enum=gateguard.models.UserRole" json:"role,omitempty"`
	Organizations   [][]byte               `protobuf:"bytes,10,rep,name=organizations,proto3" json:"organizations,omitempty"`
	PreferredStacks []int64                `protobuf:"varint,11,rep,packed,name=preferred_stacks,json=preferredStacks,proto3" json:"preferred_stacks,omitempty"`
	TrialUsed       bool                   `protobuf:"varint,12,opt,name=trial_used,json=trialUsed,proto3" json:"trial_used,omitempty"`
	EmailVerified   bool                   `protobuf:"varint,13,opt,name=email_verified,json=emailVerified,proto3" json:"email_verified,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_models_gateguard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_models_gateguard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_models_gateguard_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *User) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_UserUnknown
}

func (x *User) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *User) GetIp() uint32 {
	if x != nil {
		return x.Ip
	}
	return 0
}

func (x *User) GetRefCode() string {
	if x != nil {
		return x.RefCode
	}
	return ""
}

func (x *User) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_UserRoleUnknown
}

func (x *User) GetOrganizations() [][]byte {
	if x != nil {
		return x.Organizations
	}
	return nil
}

func (x *User) GetPreferredStacks() []int64 {
	if x != nil {
		return x.PreferredStacks
	}
	return nil
}

func (x *User) GetTrialUsed() bool {
	if x != nil {
		return x.TrialUsed
	}
	return false
}

func (x *User) GetEmailVerified() bool {
	if x != nil {
		return x.EmailVerified
	}
	return false
}

// Users is
type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*User                `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_models_gateguard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_models_gateguard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_models_gateguard_proto_rawDescGZIP(), []int{1}
}

func (x *Users) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

type Invitation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inviter       string                 `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Invitee       string                 `protobuf:"bytes,2,opt,name=invitee,proto3" json:"invitee,omitempty"`
	Organization  string                 `protobuf:"bytes,3,opt,name=organization,proto3" json:"organization,omitempty"`
	Status        InvitationStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=gateguard.models.InvitationStatus" json:"status,omitempty"`
	ReferralCode  string                 `protobuf:"bytes,5,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Role          RoleType               `protobuf:"varint,7,opt,name=role,proto3,enum=gateguard.models.RoleType" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_models_gateguard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_models_gateguard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_models_gateguard_proto_rawDescGZIP(), []int{2}
}

func (x *Invitation) GetInviter() string {
	if x != nil {
		return x.Inviter
	}
	return ""
}

func (x *Invitation) GetInvitee() string {
	if x != nil {
		return x.Invitee
	}
	return ""
}

func (x *Invitation) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *Invitation) GetStatus() InvitationStatus {
	if x != nil {
		return x.Status
	}
	return InvitationStatus_InvitationPending
}

func (x *Invitation) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *Invitation) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Invitation) GetRole() RoleType {
	if x != nil {
		return x.Role
	}
	return RoleType_RoleUnknown
}

var File_models_gateguard_proto protoreflect.FileDescriptor

const file_models_gateguard_proto_rawDesc = "" +
	"\n" +
	"\x16models_gateguard.proto\x12\x10gateguard.models\"\x9d\x03\n" +
	"\x04User\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x124\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1c.gateguard.models.UserStatusR\x06status\x12\x18\n" +
	"\acreated\x18\x06 \x01(\x03R\acreated\x12\x0e\n" +
	"\x02ip\x18\a \x01(\rR\x02ip\x12\x18\n" +
	"\arefCode\x18\b \x01(\tR\arefCode\x12.\n" +
	"\x04role\x18\t \x01(\x0e2\x1a.gateguard.models.UserRoleR\x04role\x12$\n" +
	"\rorganizations\x18\n" +
	" \x03(\fR\rorganizations\x12)\n" +
	"\x10preferred_stacks\x18\v \x03(\x03R\x0fpreferredStacks\x12\x1d\n" +
	"\n" +
	"trial_used\x18\f \x01(\bR\ttrialUsed\x12%\n" +
	"\x0eemail_verified\x18\r \x01(\bR\remailVerified\"3\n" +
	"\x05Users\x12*\n" +
	"\x04user\x18\x01 \x03(\v2\x16.gateguard.models.UserR\x04user\"\x94\x02\n" +
	"\n" +
	"Invitation\x12\x18\n" +
	"\ainviter\x18\x01 \x01(\tR\ainviter\x12\x18\n" +
	"\ainvitee\x18\x02 \x01(\tR\ainvitee\x12\"\n" +
	"\forganization\x18\x03 \x01(\tR\forganization\x12:\n" +
	"\x06status\x18\x04 \x01(\x0e2\".gateguard.models.InvitationStatusR\x06status\x12#\n" +
	"\rreferral_code\x18\x05 \x01(\tR\freferralCode\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12.\n" +
	"\x04role\x18\a \x01(\x0e2\x1a.gateguard.models.RoleTypeR\x04role*>\n" +
	"\n" +
	"UserStatus\x12\x0f\n" +
	"\vUserUnknown\x10\x00\x12\x0e\n" +
	"\n" +
	"UserActive\x10\x02\x12\x0f\n" +
	"\vUserArchive\x10\x03*o\n" +
	"\bUserRole\x12\x13\n" +
	"\x0fUserRoleUnknown\x10\x00\x12\x12\n" +
	"\x0eUserRoleCommon\x10\x01\x12\x12\n" +
	"\x0eUserRoleViewer\x10\x02\x12\x13\n" +
	"\x0fUserRoleBilling\x10\x03\x12\x11\n" +
	"\rUserRoleAdmin\x10\x04*\\\n" +
	"\bRoleType\x12\x0f\n" +
	"\vRoleUnknown\x10\x00\x12\r\n" +
	"\tRoleOwner\x10\x01\x12\x0f\n" +
	"\vRoleBilling\x10\x02\x12\x0f\n" +
	"\vRoleCreator\x10\x03\x12\x0e\n" +
	"\n" +
	"RoleCommon\x10\x04*\x9e\x01\n" +
	"\x10InvitationStatus\x12\x15\n" +
	"\x11InvitationPending\x10\x00\x12\x16\n" +
	"\x12InvitationAccepted\x10\x01\x12\x16\n" +
	"\x12InvitationDeclined\x10\x02\x12\x15\n" +
	"\x11InvitationIgnored\x10\x03\x12\x15\n" +
	"\x11InvitationRevoked\x10\x04\x12\x15\n" +
	"\x11InvitationUnknown\x10\x05B-Z+github.com/Pashteto/lia/protocols/gateguardb\x06proto3"

var (
	file_models_gateguard_proto_rawDescOnce sync.Once
	file_models_gateguard_proto_rawDescData []byte
)

func file_models_gateguard_proto_rawDescGZIP() []byte {
	file_models_gateguard_proto_rawDescOnce.Do(func() {
		file_models_gateguard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_gateguard_proto_rawDesc), len(file_models_gateguard_proto_rawDesc)))
	})
	return file_models_gateguard_proto_rawDescData
}

var file_models_gateguard_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_models_gateguard_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_models_gateguard_proto_goTypes = []any{
	(UserStatus)(0),       // 0: gateguard.models.UserStatus
	(UserRole)(0),         // 1: gateguard.models.UserRole
	(RoleType)(0),         // 2: gateguard.models.RoleType
	(InvitationStatus)(0), // 3: gateguard.models.InvitationStatus
	(*User)(nil),          // 4: gateguard.models.User
	(*Users)(nil),         // 5: gateguard.models.Users
	(*Invitation)(nil),    // 6: gateguard.models.Invitation
}
var file_models_gateguard_proto_depIdxs = []int32{
	0, // 0: gateguard.models.User.status:type_name -> gateguard.models.UserStatus
	1, // 1: gateguard.models.User.role:type_name -> gateguard.models.UserRole
	4, // 2: gateguard.models.Users.user:type_name -> gateguard.models.User
	3, // 3: gateguard.models.Invitation.status:type_name -> gateguard.models.InvitationStatus
	2, // 4: gateguard.models.Invitation.role:type_name -> gateguard.models.RoleType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_models_gateguard_proto_init() }
func file_models_gateguard_proto_init() {
	if File_models_gateguard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_gateguard_proto_rawDesc), len(file_models_gateguard_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_gateguard_proto_goTypes,
		DependencyIndexes: file_models_gateguard_proto_depIdxs,
		EnumInfos:         file_models_gateguard_proto_enumTypes,
		MessageInfos:      file_models_gateguard_proto_msgTypes,
	}.Build()
	File_models_gateguard_proto = out.File
	file_models_gateguard_proto_goTypes = nil
	file_models_gateguard_proto_depIdxs = nil
}
