// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service_gateguard.proto

package gateguard

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddOrganizationError int32

const (
	AddOrganizationError_AoeValidationError           AddOrganizationError = 0
	AddOrganizationError_AoeUserNotFound              AddOrganizationError = 1
	AddOrganizationError_AoeOrganizationAlreadyExists AddOrganizationError = 2
)

// Enum value maps for AddOrganizationError.
var (
	AddOrganizationError_name = map[int32]string{
		0: "AoeValidationError",
		1: "AoeUserNotFound",
		2: "AoeOrganizationAlreadyExists",
	}
	AddOrganizationError_value = map[string]int32{
		"AoeValidationError":           0,
		"AoeUserNotFound":              1,
		"AoeOrganizationAlreadyExists": 2,
	}
)

func (x AddOrganizationError) Enum() *AddOrganizationError {
	p := new(AddOrganizationError)
	*p = x
	return p
}

func (x AddOrganizationError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddOrganizationError) Descriptor() protoreflect.EnumDescriptor {
	return file_service_gateguard_proto_enumTypes[0].Descriptor()
}

func (AddOrganizationError) Type() protoreflect.EnumType {
	return &file_service_gateguard_proto_enumTypes[0]
}

func (x AddOrganizationError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AddOrganizationError.Descriptor instead.
func (AddOrganizationError) EnumDescriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{0}
}

type RemoveOrganizationError int32

const (
	RemoveOrganizationError_RoeValidationError      RemoveOrganizationError = 0
	RemoveOrganizationError_RoeUserNotFound         RemoveOrganizationError = 1
	RemoveOrganizationError_RoeOrganizationNotFound RemoveOrganizationError = 2
)

// Enum value maps for RemoveOrganizationError.
var (
	RemoveOrganizationError_name = map[int32]string{
		0: "RoeValidationError",
		1: "RoeUserNotFound",
		2: "RoeOrganizationNotFound",
	}
	RemoveOrganizationError_value = map[string]int32{
		"RoeValidationError":      0,
		"RoeUserNotFound":         1,
		"RoeOrganizationNotFound": 2,
	}
)

func (x RemoveOrganizationError) Enum() *RemoveOrganizationError {
	p := new(RemoveOrganizationError)
	*p = x
	return p
}

func (x RemoveOrganizationError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoveOrganizationError) Descriptor() protoreflect.EnumDescriptor {
	return file_service_gateguard_proto_enumTypes[1].Descriptor()
}

func (RemoveOrganizationError) Type() protoreflect.EnumType {
	return &file_service_gateguard_proto_enumTypes[1]
}

func (x RemoveOrganizationError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoveOrganizationError.Descriptor instead.
func (RemoveOrganizationError) EnumDescriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{1}
}

type InviteUserByEmailError int32

const (
	InviteUserByEmailError_IueValidationError              InviteUserByEmailError = 0
	InviteUserByEmailError_IueOrganizationNotFound         InviteUserByEmailError = 1
	InviteUserByEmailError_IueOrganizationInviteNotAllowed InviteUserByEmailError = 2
	InviteUserByEmailError_IueUserAlreadyExists            InviteUserByEmailError = 3
	InviteUserByEmailError_IueInvitesRateLimitReached      InviteUserByEmailError = 4
)

// Enum value maps for InviteUserByEmailError.
var (
	InviteUserByEmailError_name = map[int32]string{
		0: "IueValidationError",
		1: "IueOrganizationNotFound",
		2: "IueOrganizationInviteNotAllowed",
		3: "IueUserAlreadyExists",
		4: "IueInvitesRateLimitReached",
	}
	InviteUserByEmailError_value = map[string]int32{
		"IueValidationError":              0,
		"IueOrganizationNotFound":         1,
		"IueOrganizationInviteNotAllowed": 2,
		"IueUserAlreadyExists":            3,
		"IueInvitesRateLimitReached":      4,
	}
)

func (x InviteUserByEmailError) Enum() *InviteUserByEmailError {
	p := new(InviteUserByEmailError)
	*p = x
	return p
}

func (x InviteUserByEmailError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InviteUserByEmailError) Descriptor() protoreflect.EnumDescriptor {
	return file_service_gateguard_proto_enumTypes[2].Descriptor()
}

func (InviteUserByEmailError) Type() protoreflect.EnumType {
	return &file_service_gateguard_proto_enumTypes[2]
}

func (x InviteUserByEmailError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InviteUserByEmailError.Descriptor instead.
func (InviteUserByEmailError) EnumDescriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{2}
}

type ReactToInvitationError int32

const (
	ReactToInvitationError_RtiValidationError      ReactToInvitationError = 0
	ReactToInvitationError_RtiOrganizationConflict ReactToInvitationError = 1
	ReactToInvitationError_RtiInviteStatusConflict ReactToInvitationError = 2
	ReactToInvitationError_RtiInviteUserMismatch   ReactToInvitationError = 3
)

// Enum value maps for ReactToInvitationError.
var (
	ReactToInvitationError_name = map[int32]string{
		0: "RtiValidationError",
		1: "RtiOrganizationConflict",
		2: "RtiInviteStatusConflict",
		3: "RtiInviteUserMismatch",
	}
	ReactToInvitationError_value = map[string]int32{
		"RtiValidationError":      0,
		"RtiOrganizationConflict": 1,
		"RtiInviteStatusConflict": 2,
		"RtiInviteUserMismatch":   3,
	}
)

func (x ReactToInvitationError) Enum() *ReactToInvitationError {
	p := new(ReactToInvitationError)
	*p = x
	return p
}

func (x ReactToInvitationError) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReactToInvitationError) Descriptor() protoreflect.EnumDescriptor {
	return file_service_gateguard_proto_enumTypes[3].Descriptor()
}

func (ReactToInvitationError) Type() protoreflect.EnumType {
	return &file_service_gateguard_proto_enumTypes[3]
}

func (x ReactToInvitationError) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReactToInvitationError.Descriptor instead.
func (ReactToInvitationError) EnumDescriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{3}
}

type SetUserPreferredStacksRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserUuid        []byte                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	PreferredStacks []int64                `protobuf:"varint,2,rep,packed,name=preferred_stacks,json=preferredStacks,proto3" json:"preferred_stacks,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SetUserPreferredStacksRequest) Reset() {
	*x = SetUserPreferredStacksRequest{}
	mi := &file_service_gateguard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserPreferredStacksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserPreferredStacksRequest) ProtoMessage() {}

func (x *SetUserPreferredStacksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserPreferredStacksRequest.ProtoReflect.Descriptor instead.
func (*SetUserPreferredStacksRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{0}
}

func (x *SetUserPreferredStacksRequest) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *SetUserPreferredStacksRequest) GetPreferredStacks() []int64 {
	if x != nil {
		return x.PreferredStacks
	}
	return nil
}

type SetUserTrialUsedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      []byte                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	TrialUsed     bool                   `protobuf:"varint,2,opt,name=trial_used,json=trialUsed,proto3" json:"trial_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserTrialUsedRequest) Reset() {
	*x = SetUserTrialUsedRequest{}
	mi := &file_service_gateguard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserTrialUsedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserTrialUsedRequest) ProtoMessage() {}

func (x *SetUserTrialUsedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserTrialUsedRequest.ProtoReflect.Descriptor instead.
func (*SetUserTrialUsedRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{1}
}

func (x *SetUserTrialUsedRequest) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *SetUserTrialUsedRequest) GetTrialUsed() bool {
	if x != nil {
		return x.TrialUsed
	}
	return false
}

type UpdateUserRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      []byte                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Role          UserRole               `protobuf:"varint,2,opt,name=role,proto3,enum=gateguard.models.UserRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRoleRequest) Reset() {
	*x = UpdateUserRoleRequest{}
	mi := &file_service_gateguard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRoleRequest) ProtoMessage() {}

func (x *UpdateUserRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRoleRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateUserRoleRequest) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *UpdateUserRoleRequest) GetRole() UserRole {
	if x != nil {
		return x.Role
	}
	return UserRole_UserRoleUnknown
}

// TokenRequest is request message for methods
// that needs only session JWT
type TokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	mi := &file_service_gateguard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{3}
}

func (x *TokenRequest) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// TokenResponse is response with session JWT
type TokenResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Token                 []byte                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserCreatedOrRestored bool                   `protobuf:"varint,2,opt,name=user_created_or_restored,json=userCreatedOrRestored,proto3" json:"user_created_or_restored,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_service_gateguard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{4}
}

func (x *TokenResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *TokenResponse) GetUserCreatedOrRestored() bool {
	if x != nil {
		return x.UserCreatedOrRestored
	}
	return false
}

type UUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          []byte                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UUIDRequest) Reset() {
	*x = UUIDRequest{}
	mi := &file_service_gateguard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDRequest) ProtoMessage() {}

func (x *UUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDRequest.ProtoReflect.Descriptor instead.
func (*UUIDRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{5}
}

func (x *UUIDRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_service_gateguard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{6}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type SignUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_service_gateguard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{7}
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type PasswordSignInRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordSignInRequest) Reset() {
	*x = PasswordSignInRequest{}
	mi := &file_service_gateguard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordSignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordSignInRequest) ProtoMessage() {}

func (x *PasswordSignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordSignInRequest.ProtoReflect.Descriptor instead.
func (*PasswordSignInRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{8}
}

func (x *PasswordSignInRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PasswordSignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyEmailRequest) Reset() {
	*x = VerifyEmailRequest{}
	mi := &file_service_gateguard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEmailRequest) ProtoMessage() {}

func (x *VerifyEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEmailRequest.ProtoReflect.Descriptor instead.
func (*VerifyEmailRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *VerifyEmailRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

// AddOrganizationRequest is request message for adding an organization to a user
type AddOrganizationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserUuid         []byte                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	OrganizationUuid []byte                 `protobuf:"bytes,2,opt,name=organization_uuid,json=organizationUuid,proto3" json:"organization_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AddOrganizationRequest) Reset() {
	*x = AddOrganizationRequest{}
	mi := &file_service_gateguard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrganizationRequest) ProtoMessage() {}

func (x *AddOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrganizationRequest.ProtoReflect.Descriptor instead.
func (*AddOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{10}
}

func (x *AddOrganizationRequest) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *AddOrganizationRequest) GetOrganizationUuid() []byte {
	if x != nil {
		return x.OrganizationUuid
	}
	return nil
}

type RemoveOrganizationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserUuid         []byte                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	OrganizationUuid []byte                 `protobuf:"bytes,2,opt,name=organization_uuid,json=organizationUuid,proto3" json:"organization_uuid,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RemoveOrganizationRequest) Reset() {
	*x = RemoveOrganizationRequest{}
	mi := &file_service_gateguard_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOrganizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrganizationRequest) ProtoMessage() {}

func (x *RemoveOrganizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrganizationRequest.ProtoReflect.Descriptor instead.
func (*RemoveOrganizationRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveOrganizationRequest) GetUserUuid() []byte {
	if x != nil {
		return x.UserUuid
	}
	return nil
}

func (x *RemoveOrganizationRequest) GetOrganizationUuid() []byte {
	if x != nil {
		return x.OrganizationUuid
	}
	return nil
}

type AddOrganizationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       *Empty                 `protobuf:"bytes,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Error         *AddOrganizationError  `protobuf:"varint,2,opt,name=error,proto3,enum=gateguard.service.AddOrganizationError,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOrganizationResponse) Reset() {
	*x = AddOrganizationResponse{}
	mi := &file_service_gateguard_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOrganizationResponse) ProtoMessage() {}

func (x *AddOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOrganizationResponse.ProtoReflect.Descriptor instead.
func (*AddOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{12}
}

func (x *AddOrganizationResponse) GetSuccess() *Empty {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *AddOrganizationResponse) GetError() AddOrganizationError {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return AddOrganizationError_AoeValidationError
}

type RemoveOrganizationResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Success       *Empty                   `protobuf:"bytes,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Error         *RemoveOrganizationError `protobuf:"varint,2,opt,name=error,proto3,enum=gateguard.service.RemoveOrganizationError,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveOrganizationResponse) Reset() {
	*x = RemoveOrganizationResponse{}
	mi := &file_service_gateguard_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveOrganizationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveOrganizationResponse) ProtoMessage() {}

func (x *RemoveOrganizationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveOrganizationResponse.ProtoReflect.Descriptor instead.
func (*RemoveOrganizationResponse) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveOrganizationResponse) GetSuccess() *Empty {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *RemoveOrganizationResponse) GetError() RemoveOrganizationError {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return RemoveOrganizationError_RoeValidationError
}

type InviteUserByEmailRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Email            string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	InviterUuid      []byte                 `protobuf:"bytes,2,opt,name=inviter_uuid,json=inviterUuid,proto3" json:"inviter_uuid,omitempty"`
	InviterEmail     string                 `protobuf:"bytes,3,opt,name=inviter_email,json=inviterEmail,proto3" json:"inviter_email,omitempty"`
	OrganizationUuid []byte                 `protobuf:"bytes,4,opt,name=organization_uuid,json=organizationUuid,proto3,oneof" json:"organization_uuid,omitempty"`
	InviteeRole      string                 `protobuf:"bytes,5,opt,name=invitee_role,json=inviteeRole,proto3" json:"invitee_role,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InviteUserByEmailRequest) Reset() {
	*x = InviteUserByEmailRequest{}
	mi := &file_service_gateguard_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserByEmailRequest) ProtoMessage() {}

func (x *InviteUserByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserByEmailRequest.ProtoReflect.Descriptor instead.
func (*InviteUserByEmailRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{14}
}

func (x *InviteUserByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *InviteUserByEmailRequest) GetInviterUuid() []byte {
	if x != nil {
		return x.InviterUuid
	}
	return nil
}

func (x *InviteUserByEmailRequest) GetInviterEmail() string {
	if x != nil {
		return x.InviterEmail
	}
	return ""
}

func (x *InviteUserByEmailRequest) GetOrganizationUuid() []byte {
	if x != nil {
		return x.OrganizationUuid
	}
	return nil
}

func (x *InviteUserByEmailRequest) GetInviteeRole() string {
	if x != nil {
		return x.InviteeRole
	}
	return ""
}

type InviteUserByEmailResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Success       *Empty                  `protobuf:"bytes,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Error         *InviteUserByEmailError `protobuf:"varint,2,opt,name=error,proto3,enum=gateguard.service.InviteUserByEmailError,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InviteUserByEmailResponse) Reset() {
	*x = InviteUserByEmailResponse{}
	mi := &file_service_gateguard_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InviteUserByEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InviteUserByEmailResponse) ProtoMessage() {}

func (x *InviteUserByEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InviteUserByEmailResponse.ProtoReflect.Descriptor instead.
func (*InviteUserByEmailResponse) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{15}
}

func (x *InviteUserByEmailResponse) GetSuccess() *Empty {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *InviteUserByEmailResponse) GetError() InviteUserByEmailError {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return InviteUserByEmailError_IueValidationError
}

type AllInvitationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inviter       *string                `protobuf:"bytes,1,opt,name=inviter,proto3,oneof" json:"inviter,omitempty"`
	Invitee       *string                `protobuf:"bytes,2,opt,name=invitee,proto3,oneof" json:"invitee,omitempty"`
	Organization  []byte                 `protobuf:"bytes,3,opt,name=organization,proto3,oneof" json:"organization,omitempty"`
	Statuses      []InvitationStatus     `protobuf:"varint,4,rep,packed,name=statuses,proto3,enum=gateguard.models.InvitationStatus" json:"statuses,omitempty"`
	Limit         *int32                 `protobuf:"varint,5,opt,name=limit,proto3,oneof" json:"limit,omitempty"`
	Offset        *int32                 `protobuf:"varint,6,opt,name=offset,proto3,oneof" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllInvitationsRequest) Reset() {
	*x = AllInvitationsRequest{}
	mi := &file_service_gateguard_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllInvitationsRequest) ProtoMessage() {}

func (x *AllInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllInvitationsRequest.ProtoReflect.Descriptor instead.
func (*AllInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{16}
}

func (x *AllInvitationsRequest) GetInviter() string {
	if x != nil && x.Inviter != nil {
		return *x.Inviter
	}
	return ""
}

func (x *AllInvitationsRequest) GetInvitee() string {
	if x != nil && x.Invitee != nil {
		return *x.Invitee
	}
	return ""
}

func (x *AllInvitationsRequest) GetOrganization() []byte {
	if x != nil {
		return x.Organization
	}
	return nil
}

func (x *AllInvitationsRequest) GetStatuses() []InvitationStatus {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *AllInvitationsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *AllInvitationsRequest) GetOffset() int32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

type AllInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitations   []*Invitation          `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllInvitationsResponse) Reset() {
	*x = AllInvitationsResponse{}
	mi := &file_service_gateguard_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllInvitationsResponse) ProtoMessage() {}

func (x *AllInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllInvitationsResponse.ProtoReflect.Descriptor instead.
func (*AllInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{17}
}

func (x *AllInvitationsResponse) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

func (x *AllInvitationsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ReactToInvitationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitee       string                 `protobuf:"bytes,1,opt,name=invitee,proto3" json:"invitee,omitempty"`
	RefCode       string                 `protobuf:"bytes,2,opt,name=ref_code,json=refCode,proto3" json:"ref_code,omitempty"`
	Status        InvitationStatus       `protobuf:"varint,3,opt,name=status,proto3,enum=gateguard.models.InvitationStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactToInvitationRequest) Reset() {
	*x = ReactToInvitationRequest{}
	mi := &file_service_gateguard_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactToInvitationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactToInvitationRequest) ProtoMessage() {}

func (x *ReactToInvitationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactToInvitationRequest.ProtoReflect.Descriptor instead.
func (*ReactToInvitationRequest) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{18}
}

func (x *ReactToInvitationRequest) GetInvitee() string {
	if x != nil {
		return x.Invitee
	}
	return ""
}

func (x *ReactToInvitationRequest) GetRefCode() string {
	if x != nil {
		return x.RefCode
	}
	return ""
}

func (x *ReactToInvitationRequest) GetStatus() InvitationStatus {
	if x != nil {
		return x.Status
	}
	return InvitationStatus_InvitationPending
}

type ReactToInvitationResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Success       *Empty                  `protobuf:"bytes,1,opt,name=success,proto3,oneof" json:"success,omitempty"`
	Error         *ReactToInvitationError `protobuf:"varint,2,opt,name=error,proto3,enum=gateguard.service.ReactToInvitationError,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReactToInvitationResponse) Reset() {
	*x = ReactToInvitationResponse{}
	mi := &file_service_gateguard_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReactToInvitationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactToInvitationResponse) ProtoMessage() {}

func (x *ReactToInvitationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactToInvitationResponse.ProtoReflect.Descriptor instead.
func (*ReactToInvitationResponse) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{19}
}

func (x *ReactToInvitationResponse) GetSuccess() *Empty {
	if x != nil {
		return x.Success
	}
	return nil
}

func (x *ReactToInvitationResponse) GetError() ReactToInvitationError {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ReactToInvitationError_RtiValidationError
}

// Empty is
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_service_gateguard_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_service_gateguard_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_service_gateguard_proto_rawDescGZIP(), []int{20}
}

var File_service_gateguard_proto protoreflect.FileDescriptor

const file_service_gateguard_proto_rawDesc = "" +
	"\n" +
	"\x17service_gateguard.proto\x12\x11gateguard.service\x1a\x16models_gateguard.proto\"g\n" +
	"\x1dSetUserPreferredStacksRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\fR\buserUuid\x12)\n" +
	"\x10preferred_stacks\x18\x02 \x03(\x03R\x0fpreferredStacks\"U\n" +
	"\x17SetUserTrialUsedRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\fR\buserUuid\x12\x1d\n" +
	"\n" +
	"trial_used\x18\x02 \x01(\bR\ttrialUsed\"d\n" +
	"\x15UpdateUserRoleRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\fR\buserUuid\x12.\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1a.gateguard.models.UserRoleR\x04role\"$\n" +
	"\fTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\"^\n" +
	"\rTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\fR\x05token\x127\n" +
	"\x18user_created_or_restored\x18\x02 \x01(\bR\x15userCreatedOrRestored\"!\n" +
	"\vUUIDRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\fR\x04uuid\"$\n" +
	"\fEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"U\n" +
	"\rSignUpRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"I\n" +
	"\x15PasswordSignInRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"@\n" +
	"\x12VerifyEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"b\n" +
	"\x16AddOrganizationRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\fR\buserUuid\x12+\n" +
	"\x11organization_uuid\x18\x02 \x01(\fR\x10organizationUuid\"e\n" +
	"\x19RemoveOrganizationRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\fR\buserUuid\x12+\n" +
	"\x11organization_uuid\x18\x02 \x01(\fR\x10organizationUuid\"\xac\x01\n" +
	"\x17AddOrganizationResponse\x127\n" +
	"\asuccess\x18\x01 \x01(\v2\x18.gateguard.service.EmptyH\x00R\asuccess\x88\x01\x01\x12B\n" +
	"\x05error\x18\x02 \x01(\x0e2'.gateguard.service.AddOrganizationErrorH\x01R\x05error\x88\x01\x01B\n" +
	"\n" +
	"\b_successB\b\n" +
	"\x06_error\"\xb2\x01\n" +
	"\x1aRemoveOrganizationResponse\x127\n" +
	"\asuccess\x18\x01 \x01(\v2\x18.gateguard.service.EmptyH\x00R\asuccess\x88\x01\x01\x12E\n" +
	"\x05error\x18\x02 \x01(\x0e2*.gateguard.service.RemoveOrganizationErrorH\x01R\x05error\x88\x01\x01B\n" +
	"\n" +
	"\b_successB\b\n" +
	"\x06_error\"\xe3\x01\n" +
	"\x18InviteUserByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12!\n" +
	"\finviter_uuid\x18\x02 \x01(\fR\vinviterUuid\x12#\n" +
	"\rinviter_email\x18\x03 \x01(\tR\finviterEmail\x120\n" +
	"\x11organization_uuid\x18\x04 \x01(\fH\x00R\x10organizationUuid\x88\x01\x01\x12!\n" +
	"\finvitee_role\x18\x05 \x01(\tR\vinviteeRoleB\x14\n" +
	"\x12_organization_uuid\"\xb0\x01\n" +
	"\x19InviteUserByEmailResponse\x127\n" +
	"\asuccess\x18\x01 \x01(\v2\x18.gateguard.service.EmptyH\x00R\asuccess\x88\x01\x01\x12D\n" +
	"\x05error\x18\x02 \x01(\x0e2).gateguard.service.InviteUserByEmailErrorH\x01R\x05error\x88\x01\x01B\n" +
	"\n" +
	"\b_successB\b\n" +
	"\x06_error\"\xb4\x02\n" +
	"\x15AllInvitationsRequest\x12\x1d\n" +
	"\ainviter\x18\x01 \x01(\tH\x00R\ainviter\x88\x01\x01\x12\x1d\n" +
	"\ainvitee\x18\x02 \x01(\tH\x01R\ainvitee\x88\x01\x01\x12'\n" +
	"\forganization\x18\x03 \x01(\fH\x02R\forganization\x88\x01\x01\x12>\n" +
	"\bstatuses\x18\x04 \x03(\x0e2\".gateguard.models.InvitationStatusR\bstatuses\x12\x19\n" +
	"\x05limit\x18\x05 \x01(\x05H\x03R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\x06 \x01(\x05H\x04R\x06offset\x88\x01\x01B\n" +
	"\n" +
	"\b_inviterB\n" +
	"\n" +
	"\b_inviteeB\x0f\n" +
	"\r_organizationB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offset\"s\n" +
	"\x16AllInvitationsResponse\x12>\n" +
	"\vinvitations\x18\x01 \x03(\v2\x1c.gateguard.models.InvitationR\vinvitations\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\x8b\x01\n" +
	"\x18ReactToInvitationRequest\x12\x18\n" +
	"\ainvitee\x18\x01 \x01(\tR\ainvitee\x12\x19\n" +
	"\bref_code\x18\x02 \x01(\tR\arefCode\x12:\n" +
	"\x06status\x18\x03 \x01(\x0e2\".gateguard.models.InvitationStatusR\x06status\"\xb0\x01\n" +
	"\x19ReactToInvitationResponse\x127\n" +
	"\asuccess\x18\x01 \x01(\v2\x18.gateguard.service.EmptyH\x00R\asuccess\x88\x01\x01\x12D\n" +
	"\x05error\x18\x02 \x01(\x0e2).gateguard.service.ReactToInvitationErrorH\x01R\x05error\x88\x01\x01B\n" +
	"\n" +
	"\b_successB\b\n" +
	"\x06_error\"\a\n" +
	"\x05Empty*e\n" +
	"\x14AddOrganizationError\x12\x16\n" +
	"\x12AoeValidationError\x10\x00\x12\x13\n" +
	"\x0fAoeUserNotFound\x10\x01\x12 \n" +
	"\x1cAoeOrganizationAlreadyExists\x10\x02*c\n" +
	"\x17RemoveOrganizationError\x12\x16\n" +
	"\x12RoeValidationError\x10\x00\x12\x13\n" +
	"\x0fRoeUserNotFound\x10\x01\x12\x1b\n" +
	"\x17RoeOrganizationNotFound\x10\x02*\xac\x01\n" +
	"\x16InviteUserByEmailError\x12\x16\n" +
	"\x12IueValidationError\x10\x00\x12\x1b\n" +
	"\x17IueOrganizationNotFound\x10\x01\x12#\n" +
	"\x1fIueOrganizationInviteNotAllowed\x10\x02\x12\x18\n" +
	"\x14IueUserAlreadyExists\x10\x03\x12\x1e\n" +
	"\x1aIueInvitesRateLimitReached\x10\x04*\x85\x01\n" +
	"\x16ReactToInvitationError\x12\x16\n" +
	"\x12RtiValidationError\x10\x00\x12\x1b\n" +
	"\x17RtiOrganizationConflict\x10\x01\x12\x1b\n" +
	"\x17RtiInviteStatusConflict\x10\x02\x12\x19\n" +
	"\x15RtiInviteUserMismatch\x10\x032\xf5\r\n" +
	"\x10GateguardService\x12G\n" +
	"\vSignInOAuth\x12\x16.gateguard.models.User\x1a .gateguard.service.TokenResponse\x12D\n" +
	"\aSignOut\x12\x1f.gateguard.service.TokenRequest\x1a\x18.gateguard.service.Empty\x12D\n" +
	"\tCheckAuth\x12\x1f.gateguard.service.TokenRequest\x1a\x16.gateguard.models.User\x12X\n" +
	"\x12SignUpWithPassword\x12 .gateguard.service.SignUpRequest\x1a .gateguard.service.TokenResponse\x12`\n" +
	"\x12SignInWithPassword\x12(.gateguard.service.PasswordSignInRequest\x1a .gateguard.service.TokenResponse\x12U\n" +
	"\x18RequestEmailVerification\x12\x1f.gateguard.service.EmailRequest\x1a\x18.gateguard.service.Empty\x12N\n" +
	"\vVerifyEmail\x12%.gateguard.service.VerifyEmailRequest\x1a\x18.gateguard.service.Empty\x12N\n" +
	"\x11MarkEmailVerified\x12\x1f.gateguard.service.EmailRequest\x1a\x18.gateguard.service.Empty\x12D\n" +
	"\n" +
	"UserByUUID\x12\x1e.gateguard.service.UUIDRequest\x1a\x16.gateguard.models.User\x12F\n" +
	"\vUserByEmail\x12\x1f.gateguard.service.EmailRequest\x1a\x16.gateguard.models.User\x12G\n" +
	"\n" +
	"DeleteUser\x12\x1f.gateguard.service.TokenRequest\x1a\x18.gateguard.service.Empty\x12:\n" +
	"\x05Users\x12\x18.gateguard.service.Empty\x1a\x17.gateguard.models.Users\x12T\n" +
	"\x0eUpdateUserRole\x12(.gateguard.service.UpdateUserRoleRequest\x1a\x18.gateguard.service.Empty\x12n\n" +
	"\x15AddOrganizationToUser\x12).gateguard.service.AddOrganizationRequest\x1a*.gateguard.service.AddOrganizationResponse\x12y\n" +
	"\x1aRemoveOrganizationFromUser\x12,.gateguard.service.RemoveOrganizationRequest\x1a-.gateguard.service.RemoveOrganizationResponse\x12n\n" +
	"\x11InviteUserByEmail\x12+.gateguard.service.InviteUserByEmailRequest\x1a,.gateguard.service.InviteUserByEmailResponse\x12e\n" +
	"\x0eAllInvitations\x12(.gateguard.service.AllInvitationsRequest\x1a).gateguard.service.AllInvitationsResponse\x12n\n" +
	"\x11ReactToInvitation\x12+.gateguard.service.ReactToInvitationRequest\x1a,.gateguard.service.ReactToInvitationResponse\x12d\n" +
	"\x16SetUserPreferredStacks\x120.gateguard.service.SetUserPreferredStacksRequest\x1a\x18.gateguard.service.Empty\x12X\n" +
	"\x10SetUserTrialUsed\x12*.gateguard.service.SetUserTrialUsedRequest\x1a\x18.gateguard.service.EmptyB-Z+github.com/Pashteto/lia/protocols/gateguardb\x06proto3"

var (
	file_service_gateguard_proto_rawDescOnce sync.Once
	file_service_gateguard_proto_rawDescData []byte
)

func file_service_gateguard_proto_rawDescGZIP() []byte {
	file_service_gateguard_proto_rawDescOnce.Do(func() {
		file_service_gateguard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_gateguard_proto_rawDesc), len(file_service_gateguard_proto_rawDesc)))
	})
	return file_service_gateguard_proto_rawDescData
}

var file_service_gateguard_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_service_gateguard_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_service_gateguard_proto_goTypes = []any{
	(AddOrganizationError)(0),             // 0: gateguard.service.AddOrganizationError
	(RemoveOrganizationError)(0),          // 1: gateguard.service.RemoveOrganizationError
	(InviteUserByEmailError)(0),           // 2: gateguard.service.InviteUserByEmailError
	(ReactToInvitationError)(0),           // 3: gateguard.service.ReactToInvitationError
	(*SetUserPreferredStacksRequest)(nil), // 4: gateguard.service.SetUserPreferredStacksRequest
	(*SetUserTrialUsedRequest)(nil),       // 5: gateguard.service.SetUserTrialUsedRequest
	(*UpdateUserRoleRequest)(nil),         // 6: gateguard.service.UpdateUserRoleRequest
	(*TokenRequest)(nil),                  // 7: gateguard.service.TokenRequest
	(*TokenResponse)(nil),                 // 8: gateguard.service.TokenResponse
	(*UUIDRequest)(nil),                   // 9: gateguard.service.UUIDRequest
	(*EmailRequest)(nil),                  // 10: gateguard.service.EmailRequest
	(*SignUpRequest)(nil),                 // 11: gateguard.service.SignUpRequest
	(*PasswordSignInRequest)(nil),         // 12: gateguard.service.PasswordSignInRequest
	(*VerifyEmailRequest)(nil),            // 13: gateguard.service.VerifyEmailRequest
	(*AddOrganizationRequest)(nil),        // 14: gateguard.service.AddOrganizationRequest
	(*RemoveOrganizationRequest)(nil),     // 15: gateguard.service.RemoveOrganizationRequest
	(*AddOrganizationResponse)(nil),       // 16: gateguard.service.AddOrganizationResponse
	(*RemoveOrganizationResponse)(nil),    // 17: gateguard.service.RemoveOrganizationResponse
	(*InviteUserByEmailRequest)(nil),      // 18: gateguard.service.InviteUserByEmailRequest
	(*InviteUserByEmailResponse)(nil),     // 19: gateguard.service.InviteUserByEmailResponse
	(*AllInvitationsRequest)(nil),         // 20: gateguard.service.AllInvitationsRequest
	(*AllInvitationsResponse)(nil),        // 21: gateguard.service.AllInvitationsResponse
	(*ReactToInvitationRequest)(nil),      // 22: gateguard.service.ReactToInvitationRequest
	(*ReactToInvitationResponse)(nil),     // 23: gateguard.service.ReactToInvitationResponse
	(*Empty)(nil),                         // 24: gateguard.service.Empty
	(UserRole)(0),                         // 25: gateguard.models.UserRole
	(InvitationStatus)(0),                 // 26: gateguard.models.InvitationStatus
	(*Invitation)(nil),                    // 27: gateguard.models.Invitation
	(*User)(nil),                          // 28: gateguard.models.User
	(*Users)(nil),                         // 29: gateguard.models.Users
}
var file_service_gateguard_proto_depIdxs = []int32{
	25, // 0: gateguard.service.UpdateUserRoleRequest.role:type_name -> gateguard.models.UserRole
	24, // 1: gateguard.service.AddOrganizationResponse.success:type_name -> gateguard.service.Empty
	0,  // 2: gateguard.service.AddOrganizationResponse.error:type_name -> gateguard.service.AddOrganizationError
	24, // 3: gateguard.service.RemoveOrganizationResponse.success:type_name -> gateguard.service.Empty
	1,  // 4: gateguard.service.RemoveOrganizationResponse.error:type_name -> gateguard.service.RemoveOrganizationError
	24, // 5: gateguard.service.InviteUserByEmailResponse.success:type_name -> gateguard.service.Empty
	2,  // 6: gateguard.service.InviteUserByEmailResponse.error:type_name -> gateguard.service.InviteUserByEmailError
	26, // 7: gateguard.service.AllInvitationsRequest.statuses:type_name -> gateguard.models.InvitationStatus
	27, // 8: gateguard.service.AllInvitationsResponse.invitations:type_name -> gateguard.models.Invitation
	26, // 9: gateguard.service.ReactToInvitationRequest.status:type_name -> gateguard.models.InvitationStatus
	24, // 10: gateguard.service.ReactToInvitationResponse.success:type_name -> gateguard.service.Empty
	3,  // 11: gateguard.service.ReactToInvitationResponse.error:type_name -> gateguard.service.ReactToInvitationError
	28, // 12: gateguard.service.GateguardService.SignInOAuth:input_type -> gateguard.models.User
	7,  // 13: gateguard.service.GateguardService.SignOut:input_type -> gateguard.service.TokenRequest
	7,  // 14: gateguard.service.GateguardService.CheckAuth:input_type -> gateguard.service.TokenRequest
	11, // 15: gateguard.service.GateguardService.SignUpWithPassword:input_type -> gateguard.service.SignUpRequest
	12, // 16: gateguard.service.GateguardService.SignInWithPassword:input_type -> gateguard.service.PasswordSignInRequest
	10, // 17: gateguard.service.GateguardService.RequestEmailVerification:input_type -> gateguard.service.EmailRequest
	13, // 18: gateguard.service.GateguardService.VerifyEmail:input_type -> gateguard.service.VerifyEmailRequest
	10, // 19: gateguard.service.GateguardService.MarkEmailVerified:input_type -> gateguard.service.EmailRequest
	9,  // 20: gateguard.service.GateguardService.UserByUUID:input_type -> gateguard.service.UUIDRequest
	10, // 21: gateguard.service.GateguardService.UserByEmail:input_type -> gateguard.service.EmailRequest
	7,  // 22: gateguard.service.GateguardService.DeleteUser:input_type -> gateguard.service.TokenRequest
	24, // 23: gateguard.service.GateguardService.Users:input_type -> gateguard.service.Empty
	6,  // 24: gateguard.service.GateguardService.UpdateUserRole:input_type -> gateguard.service.UpdateUserRoleRequest
	14, // 25: gateguard.service.GateguardService.AddOrganizationToUser:input_type -> gateguard.service.AddOrganizationRequest
	15, // 26: gateguard.service.GateguardService.RemoveOrganizationFromUser:input_type -> gateguard.service.RemoveOrganizationRequest
	18, // 27: gateguard.service.GateguardService.InviteUserByEmail:input_type -> gateguard.service.InviteUserByEmailRequest
	20, // 28: gateguard.service.GateguardService.AllInvitations:input_type -> gateguard.service.AllInvitationsRequest
	22, // 29: gateguard.service.GateguardService.ReactToInvitation:input_type -> gateguard.service.ReactToInvitationRequest
	4,  // 30: gateguard.service.GateguardService.SetUserPreferredStacks:input_type -> gateguard.service.SetUserPreferredStacksRequest
	5,  // 31: gateguard.service.GateguardService.SetUserTrialUsed:input_type -> gateguard.service.SetUserTrialUsedRequest
	8,  // 32: gateguard.service.GateguardService.SignInOAuth:output_type -> gateguard.service.TokenResponse
	24, // 33: gateguard.service.GateguardService.SignOut:output_type -> gateguard.service.Empty
	28, // 34: gateguard.service.GateguardService.CheckAuth:output_type -> gateguard.models.User
	8,  // 35: gateguard.service.GateguardService.SignUpWithPassword:output_type -> gateguard.service.TokenResponse
	8,  // 36: gateguard.service.GateguardService.SignInWithPassword:output_type -> gateguard.service.TokenResponse
	24, // 37: gateguard.service.GateguardService.RequestEmailVerification:output_type -> gateguard.service.Empty
	24, // 38: gateguard.service.GateguardService.VerifyEmail:output_type -> gateguard.service.Empty
	24, // 39: gateguard.service.GateguardService.MarkEmailVerified:output_type -> gateguard.service.Empty
	28, // 40: gateguard.service.GateguardService.UserByUUID:output_type -> gateguard.models.User
	28, // 41: gateguard.service.GateguardService.UserByEmail:output_type -> gateguard.models.User
	24, // 42: gateguard.service.GateguardService.DeleteUser:output_type -> gateguard.service.Empty
	29, // 43: gateguard.service.GateguardService.Users:output_type -> gateguard.models.Users
	24, // 44: gateguard.service.GateguardService.UpdateUserRole:output_type -> gateguard.service.Empty
	16, // 45: gateguard.service.GateguardService.AddOrganizationToUser:output_type -> gateguard.service.AddOrganizationResponse
	17, // 46: gateguard.service.GateguardService.RemoveOrganizationFromUser:output_type -> gateguard.service.RemoveOrganizationResponse
	19, // 47: gateguard.service.GateguardService.InviteUserByEmail:output_type -> gateguard.service.InviteUserByEmailResponse
	21, // 48: gateguard.service.GateguardService.AllInvitations:output_type -> gateguard.service.AllInvitationsResponse
	23, // 49: gateguard.service.GateguardService.ReactToInvitation:output_type -> gateguard.service.ReactToInvitationResponse
	24, // 50: gateguard.service.GateguardService.SetUserPreferredStacks:output_type -> gateguard.service.Empty
	24, // 51: gateguard.service.GateguardService.SetUserTrialUsed:output_type -> gateguard.service.Empty
	32, // [32:52] is the sub-list for method output_type
	12, // [12:32] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_service_gateguard_proto_init() }
func file_service_gateguard_proto_init() {
	if File_service_gateguard_proto != nil {
		return
	}
	file_models_gateguard_proto_init()
	file_service_gateguard_proto_msgTypes[12].OneofWrappers = []any{}
	file_service_gateguard_proto_msgTypes[13].OneofWrappers = []any{}
	file_service_gateguard_proto_msgTypes[14].OneofWrappers = []any{}
	file_service_gateguard_proto_msgTypes[15].OneofWrappers = []any{}
	file_service_gateguard_proto_msgTypes[16].OneofWrappers = []any{}
	file_service_gateguard_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_gateguard_proto_rawDesc), len(file_service_gateguard_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_gateguard_proto_goTypes,
		DependencyIndexes: file_service_gateguard_proto_depIdxs,
		EnumInfos:         file_service_gateguard_proto_enumTypes,
		MessageInfos:      file_service_gateguard_proto_msgTypes,
	}.Build()
	File_service_gateguard_proto = out.File
	file_service_gateguard_proto_goTypes = nil
	file_service_gateguard_proto_depIdxs = nil
}
