// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: service_gateguard.proto

package gateguard

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GateguardService_SignInOAuth_FullMethodName                = "/gateguard.service.GateguardService/SignInOAuth"
	GateguardService_SignOut_FullMethodName                    = "/gateguard.service.GateguardService/SignOut"
	GateguardService_CheckAuth_FullMethodName                  = "/gateguard.service.GateguardService/CheckAuth"
	GateguardService_SignUpWithPassword_FullMethodName         = "/gateguard.service.GateguardService/SignUpWithPassword"
	GateguardService_SignInWithPassword_FullMethodName         = "/gateguard.service.GateguardService/SignInWithPassword"
	GateguardService_RequestEmailVerification_FullMethodName   = "/gateguard.service.GateguardService/RequestEmailVerification"
	GateguardService_VerifyEmail_FullMethodName                = "/gateguard.service.GateguardService/VerifyEmail"
	GateguardService_UserByUUID_FullMethodName                 = "/gateguard.service.GateguardService/UserByUUID"
	GateguardService_UserByEmail_FullMethodName                = "/gateguard.service.GateguardService/UserByEmail"
	GateguardService_DeleteUser_FullMethodName                 = "/gateguard.service.GateguardService/DeleteUser"
	GateguardService_Users_FullMethodName                      = "/gateguard.service.GateguardService/Users"
	GateguardService_UpdateUserRole_FullMethodName             = "/gateguard.service.GateguardService/UpdateUserRole"
	GateguardService_AddOrganizationToUser_FullMethodName      = "/gateguard.service.GateguardService/AddOrganizationToUser"
	GateguardService_RemoveOrganizationFromUser_FullMethodName = "/gateguard.service.GateguardService/RemoveOrganizationFromUser"
	GateguardService_InviteUserByEmail_FullMethodName          = "/gateguard.service.GateguardService/InviteUserByEmail"
	GateguardService_AllInvitations_FullMethodName             = "/gateguard.service.GateguardService/AllInvitations"
	GateguardService_ReactToInvitation_FullMethodName          = "/gateguard.service.GateguardService/ReactToInvitation"
	GateguardService_SetUserPreferredStacks_FullMethodName     = "/gateguard.service.GateguardService/SetUserPreferredStacks"
	GateguardService_SetUserTrialUsed_FullMethodName           = "/gateguard.service.GateguardService/SetUserTrialUsed"
)

// GateguardServiceClient is the client API for GateguardService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GateguardService is GRPC server implementation
// for gateguard requests
type GateguardServiceClient interface {
	// SignInOAuth is
	SignInOAuth(ctx context.Context, in *User, opts ...grpc.CallOption) (*TokenResponse, error)
	// SignOut is
	SignOut(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*Empty, error)
	// CheckAuth is
	CheckAuth(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*User, error)
	// SignUpWithPassword creates a credentialed account and returns a session JWT.
	SignUpWithPassword(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	// SignInWithPassword verifies a password and returns a session JWT.
	SignInWithPassword(ctx context.Context, in *PasswordSignInRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	// RequestEmailVerification (STUB) issues + persists a token; does not email yet.
	RequestEmailVerification(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*Empty, error)
	// VerifyEmail (STUB) marks the account verified if the token matches.
	VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*Empty, error)
	UserByUUID(ctx context.Context, in *UUIDRequest, opts ...grpc.CallOption) (*User, error)
	UserByEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*User, error)
	// DeleteUser is
	DeleteUser(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*Empty, error)
	// Users is
	Users(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Users, error)
	UpdateUserRole(ctx context.Context, in *UpdateUserRoleRequest, opts ...grpc.CallOption) (*Empty, error)
	// AddOrganizationToUser is
	AddOrganizationToUser(ctx context.Context, in *AddOrganizationRequest, opts ...grpc.CallOption) (*AddOrganizationResponse, error)
	// RemoveOrganizationFromUser is
	RemoveOrganizationFromUser(ctx context.Context, in *RemoveOrganizationRequest, opts ...grpc.CallOption) (*RemoveOrganizationResponse, error)
	// InviteUserByEmail is
	InviteUserByEmail(ctx context.Context, in *InviteUserByEmailRequest, opts ...grpc.CallOption) (*InviteUserByEmailResponse, error)
	// AllInvitations is
	AllInvitations(ctx context.Context, in *AllInvitationsRequest, opts ...grpc.CallOption) (*AllInvitationsResponse, error)
	// ReactToInvitation is
	ReactToInvitation(ctx context.Context, in *ReactToInvitationRequest, opts ...grpc.CallOption) (*ReactToInvitationResponse, error)
	// SetUserPreferredStacks is
	SetUserPreferredStacks(ctx context.Context, in *SetUserPreferredStacksRequest, opts ...grpc.CallOption) (*Empty, error)
	// SetUserPreferredStacks is
	SetUserTrialUsed(ctx context.Context, in *SetUserTrialUsedRequest, opts ...grpc.CallOption) (*Empty, error)
}

type gateguardServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGateguardServiceClient(cc grpc.ClientConnInterface) GateguardServiceClient {
	return &gateguardServiceClient{cc}
}

func (c *gateguardServiceClient) SignInOAuth(ctx context.Context, in *User, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, GateguardService_SignInOAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) SignOut(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GateguardService_SignOut_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) CheckAuth(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GateguardService_CheckAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) SignUpWithPassword(ctx context.Context, in *SignUpRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, GateguardService_SignUpWithPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) SignInWithPassword(ctx context.Context, in *PasswordSignInRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, GateguardService_SignInWithPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) RequestEmailVerification(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GateguardService_RequestEmailVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) VerifyEmail(ctx context.Context, in *VerifyEmailRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GateguardService_VerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) UserByUUID(ctx context.Context, in *UUIDRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GateguardService_UserByUUID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) UserByEmail(ctx context.Context, in *EmailRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, GateguardService_UserByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) DeleteUser(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GateguardService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) Users(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Users, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Users)
	err := c.cc.Invoke(ctx, GateguardService_Users_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) UpdateUserRole(ctx context.Context, in *UpdateUserRoleRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GateguardService_UpdateUserRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) AddOrganizationToUser(ctx context.Context, in *AddOrganizationRequest, opts ...grpc.CallOption) (*AddOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddOrganizationResponse)
	err := c.cc.Invoke(ctx, GateguardService_AddOrganizationToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) RemoveOrganizationFromUser(ctx context.Context, in *RemoveOrganizationRequest, opts ...grpc.CallOption) (*RemoveOrganizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveOrganizationResponse)
	err := c.cc.Invoke(ctx, GateguardService_RemoveOrganizationFromUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) InviteUserByEmail(ctx context.Context, in *InviteUserByEmailRequest, opts ...grpc.CallOption) (*InviteUserByEmailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteUserByEmailResponse)
	err := c.cc.Invoke(ctx, GateguardService_InviteUserByEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) AllInvitations(ctx context.Context, in *AllInvitationsRequest, opts ...grpc.CallOption) (*AllInvitationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AllInvitationsResponse)
	err := c.cc.Invoke(ctx, GateguardService_AllInvitations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) ReactToInvitation(ctx context.Context, in *ReactToInvitationRequest, opts ...grpc.CallOption) (*ReactToInvitationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReactToInvitationResponse)
	err := c.cc.Invoke(ctx, GateguardService_ReactToInvitation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) SetUserPreferredStacks(ctx context.Context, in *SetUserPreferredStacksRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GateguardService_SetUserPreferredStacks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateguardServiceClient) SetUserTrialUsed(ctx context.Context, in *SetUserTrialUsedRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, GateguardService_SetUserTrialUsed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GateguardServiceServer is the server API for GateguardService service.
// All implementations must embed UnimplementedGateguardServiceServer
// for forward compatibility.
//
// GateguardService is GRPC server implementation
// for gateguard requests
type GateguardServiceServer interface {
	// SignInOAuth is
	SignInOAuth(context.Context, *User) (*TokenResponse, error)
	// SignOut is
	SignOut(context.Context, *TokenRequest) (*Empty, error)
	// CheckAuth is
	CheckAuth(context.Context, *TokenRequest) (*User, error)
	// SignUpWithPassword creates a credentialed account and returns a session JWT.
	SignUpWithPassword(context.Context, *SignUpRequest) (*TokenResponse, error)
	// SignInWithPassword verifies a password and returns a session JWT.
	SignInWithPassword(context.Context, *PasswordSignInRequest) (*TokenResponse, error)
	// RequestEmailVerification (STUB) issues + persists a token; does not email yet.
	RequestEmailVerification(context.Context, *EmailRequest) (*Empty, error)
	// VerifyEmail (STUB) marks the account verified if the token matches.
	VerifyEmail(context.Context, *VerifyEmailRequest) (*Empty, error)
	UserByUUID(context.Context, *UUIDRequest) (*User, error)
	UserByEmail(context.Context, *EmailRequest) (*User, error)
	// DeleteUser is
	DeleteUser(context.Context, *TokenRequest) (*Empty, error)
	// Users is
	Users(context.Context, *Empty) (*Users, error)
	UpdateUserRole(context.Context, *UpdateUserRoleRequest) (*Empty, error)
	// AddOrganizationToUser is
	AddOrganizationToUser(context.Context, *AddOrganizationRequest) (*AddOrganizationResponse, error)
	// RemoveOrganizationFromUser is
	RemoveOrganizationFromUser(context.Context, *RemoveOrganizationRequest) (*RemoveOrganizationResponse, error)
	// InviteUserByEmail is
	InviteUserByEmail(context.Context, *InviteUserByEmailRequest) (*InviteUserByEmailResponse, error)
	// AllInvitations is
	AllInvitations(context.Context, *AllInvitationsRequest) (*AllInvitationsResponse, error)
	// ReactToInvitation is
	ReactToInvitation(context.Context, *ReactToInvitationRequest) (*ReactToInvitationResponse, error)
	// SetUserPreferredStacks is
	SetUserPreferredStacks(context.Context, *SetUserPreferredStacksRequest) (*Empty, error)
	// SetUserPreferredStacks is
	SetUserTrialUsed(context.Context, *SetUserTrialUsedRequest) (*Empty, error)
	mustEmbedUnimplementedGateguardServiceServer()
}

// UnimplementedGateguardServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGateguardServiceServer struct{}

func (UnimplementedGateguardServiceServer) SignInOAuth(context.Context, *User) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignInOAuth not implemented")
}
func (UnimplementedGateguardServiceServer) SignOut(context.Context, *TokenRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SignOut not implemented")
}
func (UnimplementedGateguardServiceServer) CheckAuth(context.Context, *TokenRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAuth not implemented")
}
func (UnimplementedGateguardServiceServer) SignUpWithPassword(context.Context, *SignUpRequest) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignUpWithPassword not implemented")
}
func (UnimplementedGateguardServiceServer) SignInWithPassword(context.Context, *PasswordSignInRequest) (*TokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignInWithPassword not implemented")
}
func (UnimplementedGateguardServiceServer) RequestEmailVerification(context.Context, *EmailRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestEmailVerification not implemented")
}
func (UnimplementedGateguardServiceServer) VerifyEmail(context.Context, *VerifyEmailRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyEmail not implemented")
}
func (UnimplementedGateguardServiceServer) UserByUUID(context.Context, *UUIDRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method UserByUUID not implemented")
}
func (UnimplementedGateguardServiceServer) UserByEmail(context.Context, *EmailRequest) (*User, error) {
	return nil, status.Error(codes.Unimplemented, "method UserByEmail not implemented")
}
func (UnimplementedGateguardServiceServer) DeleteUser(context.Context, *TokenRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUser not implemented")
}
func (UnimplementedGateguardServiceServer) Users(context.Context, *Empty) (*Users, error) {
	return nil, status.Error(codes.Unimplemented, "method Users not implemented")
}
func (UnimplementedGateguardServiceServer) UpdateUserRole(context.Context, *UpdateUserRoleRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUserRole not implemented")
}
func (UnimplementedGateguardServiceServer) AddOrganizationToUser(context.Context, *AddOrganizationRequest) (*AddOrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddOrganizationToUser not implemented")
}
func (UnimplementedGateguardServiceServer) RemoveOrganizationFromUser(context.Context, *RemoveOrganizationRequest) (*RemoveOrganizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveOrganizationFromUser not implemented")
}
func (UnimplementedGateguardServiceServer) InviteUserByEmail(context.Context, *InviteUserByEmailRequest) (*InviteUserByEmailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteUserByEmail not implemented")
}
func (UnimplementedGateguardServiceServer) AllInvitations(context.Context, *AllInvitationsRequest) (*AllInvitationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AllInvitations not implemented")
}
func (UnimplementedGateguardServiceServer) ReactToInvitation(context.Context, *ReactToInvitationRequest) (*ReactToInvitationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReactToInvitation not implemented")
}
func (UnimplementedGateguardServiceServer) SetUserPreferredStacks(context.Context, *SetUserPreferredStacksRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserPreferredStacks not implemented")
}
func (UnimplementedGateguardServiceServer) SetUserTrialUsed(context.Context, *SetUserTrialUsedRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUserTrialUsed not implemented")
}
func (UnimplementedGateguardServiceServer) mustEmbedUnimplementedGateguardServiceServer() {}
func (UnimplementedGateguardServiceServer) testEmbeddedByValue()                          {}

// UnsafeGateguardServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GateguardServiceServer will
// result in compilation errors.
type UnsafeGateguardServiceServer interface {
	mustEmbedUnimplementedGateguardServiceServer()
}

func RegisterGateguardServiceServer(s grpc.ServiceRegistrar, srv GateguardServiceServer) {
	// If the following call panics, it indicates UnimplementedGateguardServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GateguardService_ServiceDesc, srv)
}

func _GateguardService_SignInOAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).SignInOAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_SignInOAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).SignInOAuth(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_SignOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).SignOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_SignOut_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).SignOut(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_CheckAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).CheckAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_CheckAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).CheckAuth(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_SignUpWithPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).SignUpWithPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_SignUpWithPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).SignUpWithPassword(ctx, req.(*SignUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_SignInWithPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasswordSignInRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).SignInWithPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_SignInWithPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).SignInWithPassword(ctx, req.(*PasswordSignInRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_RequestEmailVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).RequestEmailVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_RequestEmailVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).RequestEmailVerification(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_VerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).VerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_VerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).VerifyEmail(ctx, req.(*VerifyEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_UserByUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UUIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).UserByUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_UserByUUID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).UserByUUID(ctx, req.(*UUIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_UserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).UserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_UserByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).UserByEmail(ctx, req.(*EmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_DeleteUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).DeleteUser(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_Users_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).Users(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_Users_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).Users(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_UpdateUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).UpdateUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_UpdateUserRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).UpdateUserRole(ctx, req.(*UpdateUserRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_AddOrganizationToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).AddOrganizationToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_AddOrganizationToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).AddOrganizationToUser(ctx, req.(*AddOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_RemoveOrganizationFromUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).RemoveOrganizationFromUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_RemoveOrganizationFromUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).RemoveOrganizationFromUser(ctx, req.(*RemoveOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_InviteUserByEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteUserByEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).InviteUserByEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_InviteUserByEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).InviteUserByEmail(ctx, req.(*InviteUserByEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_AllInvitations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllInvitationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).AllInvitations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_AllInvitations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).AllInvitations(ctx, req.(*AllInvitationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_ReactToInvitation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReactToInvitationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).ReactToInvitation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_ReactToInvitation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).ReactToInvitation(ctx, req.(*ReactToInvitationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_SetUserPreferredStacks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserPreferredStacksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).SetUserPreferredStacks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_SetUserPreferredStacks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).SetUserPreferredStacks(ctx, req.(*SetUserPreferredStacksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateguardService_SetUserTrialUsed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserTrialUsedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateguardServiceServer).SetUserTrialUsed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateguardService_SetUserTrialUsed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateguardServiceServer).SetUserTrialUsed(ctx, req.(*SetUserTrialUsedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GateguardService_ServiceDesc is the grpc.ServiceDesc for GateguardService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GateguardService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateguard.service.GateguardService",
	HandlerType: (*GateguardServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SignInOAuth",
			Handler:    _GateguardService_SignInOAuth_Handler,
		},
		{
			MethodName: "SignOut",
			Handler:    _GateguardService_SignOut_Handler,
		},
		{
			MethodName: "CheckAuth",
			Handler:    _GateguardService_CheckAuth_Handler,
		},
		{
			MethodName: "SignUpWithPassword",
			Handler:    _GateguardService_SignUpWithPassword_Handler,
		},
		{
			MethodName: "SignInWithPassword",
			Handler:    _GateguardService_SignInWithPassword_Handler,
		},
		{
			MethodName: "RequestEmailVerification",
			Handler:    _GateguardService_RequestEmailVerification_Handler,
		},
		{
			MethodName: "VerifyEmail",
			Handler:    _GateguardService_VerifyEmail_Handler,
		},
		{
			MethodName: "UserByUUID",
			Handler:    _GateguardService_UserByUUID_Handler,
		},
		{
			MethodName: "UserByEmail",
			Handler:    _GateguardService_UserByEmail_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _GateguardService_DeleteUser_Handler,
		},
		{
			MethodName: "Users",
			Handler:    _GateguardService_Users_Handler,
		},
		{
			MethodName: "UpdateUserRole",
			Handler:    _GateguardService_UpdateUserRole_Handler,
		},
		{
			MethodName: "AddOrganizationToUser",
			Handler:    _GateguardService_AddOrganizationToUser_Handler,
		},
		{
			MethodName: "RemoveOrganizationFromUser",
			Handler:    _GateguardService_RemoveOrganizationFromUser_Handler,
		},
		{
			MethodName: "InviteUserByEmail",
			Handler:    _GateguardService_InviteUserByEmail_Handler,
		},
		{
			MethodName: "AllInvitations",
			Handler:    _GateguardService_AllInvitations_Handler,
		},
		{
			MethodName: "ReactToInvitation",
			Handler:    _GateguardService_ReactToInvitation_Handler,
		},
		{
			MethodName: "SetUserPreferredStacks",
			Handler:    _GateguardService_SetUserPreferredStacks_Handler,
		},
		{
			MethodName: "SetUserTrialUsed",
			Handler:    _GateguardService_SetUserTrialUsed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service_gateguard.proto",
}
