// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "gateguard/internal/pkg/clients/organizations/models"

	mock "github.com/stretchr/testify/mock"

	organizations "gateguard/internal/pkg/clients/organizations"

	uuid "github.com/gofrs/uuid"
)

// IOrganizationsAPI is an autogenerated mock type for the IOrganizationsAPI type
type IOrganizationsAPI struct {
	mock.Mock
}

type IOrganizationsAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *IOrganizationsAPI) EXPECT() *IOrganizationsAPI_Expecter {
	return &IOrganizationsAPI_Expecter{mock: &_m.Mock}
}

// AddUserToOrganization provides a mock function with given fields: ctx, params
func (_m *IOrganizationsAPI) AddUserToOrganization(ctx context.Context, params organizations.AddUserParams) (*models.Organization, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for AddUserToOrganization")
	}

	var r0 *models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, organizations.AddUserParams) (*models.Organization, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, organizations.AddUserParams) *models.Organization); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, organizations.AddUserParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrganizationsAPI_AddUserToOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddUserToOrganization'
type IOrganizationsAPI_AddUserToOrganization_Call struct {
	*mock.Call
}

// AddUserToOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - params organizations.AddUserParams
func (_e *IOrganizationsAPI_Expecter) AddUserToOrganization(ctx interface{}, params interface{}) *IOrganizationsAPI_AddUserToOrganization_Call {
	return &IOrganizationsAPI_AddUserToOrganization_Call{Call: _e.mock.On("AddUserToOrganization", ctx, params)}
}

func (_c *IOrganizationsAPI_AddUserToOrganization_Call) Run(run func(ctx context.Context, params organizations.AddUserParams)) *IOrganizationsAPI_AddUserToOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(organizations.AddUserParams))
	})
	return _c
}

func (_c *IOrganizationsAPI_AddUserToOrganization_Call) Return(_a0 *models.Organization, _a1 error) *IOrganizationsAPI_AddUserToOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrganizationsAPI_AddUserToOrganization_Call) RunAndReturn(run func(context.Context, organizations.AddUserParams) (*models.Organization, error)) *IOrganizationsAPI_AddUserToOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// CheckOrganizationInvitationOperationAvailability provides a mock function with given fields: ctx, params
func (_m *IOrganizationsAPI) CheckOrganizationInvitationOperationAvailability(ctx context.Context, params organizations.CheckOrganizationInvitationOperationAvailabilityParams) (bool, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CheckOrganizationInvitationOperationAvailability")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, organizations.CheckOrganizationInvitationOperationAvailabilityParams) (bool, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, organizations.CheckOrganizationInvitationOperationAvailabilityParams) bool); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, organizations.CheckOrganizationInvitationOperationAvailabilityParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrganizationsAPI_CheckOrganizationInvitationOperationAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckOrganizationInvitationOperationAvailability'
type IOrganizationsAPI_CheckOrganizationInvitationOperationAvailability_Call struct {
	*mock.Call
}

// CheckOrganizationInvitationOperationAvailability is a helper method to define mock.On call
//   - ctx context.Context
//   - params organizations.CheckOrganizationInvitationOperationAvailabilityParams
func (_e *IOrganizationsAPI_Expecter) CheckOrganizationInvitationOperationAvailability(ctx interface{}, params interface{}) *IOrganizationsAPI_CheckOrganizationInvitationOperationAvailability_Call {
	return &IOrganizationsAPI_CheckOrganizationInvitationOperationAvailability_Call{Call: _e.mock.On("CheckOrganizationInvitationOperationAvailability", ctx, params)}
}

func (_c *IOrganizationsAPI_CheckOrganizationInvitationOperationAvailability_Call) Run(run func(ctx context.Context, params organizations.CheckOrganizationInvitationOperationAvailabilityParams)) *IOrganizationsAPI_CheckOrganizationInvitationOperationAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(organizations.CheckOrganizationInvitationOperationAvailabilityParams))
	})
	return _c
}

func (_c *IOrganizationsAPI_CheckOrganizationInvitationOperationAvailability_Call) Return(_a0 bool, _a1 error) *IOrganizationsAPI_CheckOrganizationInvitationOperationAvailability_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrganizationsAPI_CheckOrganizationInvitationOperationAvailability_Call) RunAndReturn(run func(context.Context, organizations.CheckOrganizationInvitationOperationAvailabilityParams) (bool, error)) *IOrganizationsAPI_CheckOrganizationInvitationOperationAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// CheckOrganizationOperationAvailability provides a mock function with given fields: ctx, params
func (_m *IOrganizationsAPI) CheckOrganizationOperationAvailability(ctx context.Context, params organizations.CheckOrganizationOperationAvailabilityParams) (bool, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CheckOrganizationOperationAvailability")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, organizations.CheckOrganizationOperationAvailabilityParams) (bool, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, organizations.CheckOrganizationOperationAvailabilityParams) bool); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, organizations.CheckOrganizationOperationAvailabilityParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrganizationsAPI_CheckOrganizationOperationAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckOrganizationOperationAvailability'
type IOrganizationsAPI_CheckOrganizationOperationAvailability_Call struct {
	*mock.Call
}

// CheckOrganizationOperationAvailability is a helper method to define mock.On call
//   - ctx context.Context
//   - params organizations.CheckOrganizationOperationAvailabilityParams
func (_e *IOrganizationsAPI_Expecter) CheckOrganizationOperationAvailability(ctx interface{}, params interface{}) *IOrganizationsAPI_CheckOrganizationOperationAvailability_Call {
	return &IOrganizationsAPI_CheckOrganizationOperationAvailability_Call{Call: _e.mock.On("CheckOrganizationOperationAvailability", ctx, params)}
}

func (_c *IOrganizationsAPI_CheckOrganizationOperationAvailability_Call) Run(run func(ctx context.Context, params organizations.CheckOrganizationOperationAvailabilityParams)) *IOrganizationsAPI_CheckOrganizationOperationAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(organizations.CheckOrganizationOperationAvailabilityParams))
	})
	return _c
}

func (_c *IOrganizationsAPI_CheckOrganizationOperationAvailability_Call) Return(_a0 bool, _a1 error) *IOrganizationsAPI_CheckOrganizationOperationAvailability_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrganizationsAPI_CheckOrganizationOperationAvailability_Call) RunAndReturn(run func(context.Context, organizations.CheckOrganizationOperationAvailabilityParams) (bool, error)) *IOrganizationsAPI_CheckOrganizationOperationAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// CheckRollupsOperationAvailability provides a mock function with given fields: ctx, params
func (_m *IOrganizationsAPI) CheckRollupsOperationAvailability(ctx context.Context, params organizations.CheckRollupsOperationAvailabilityParams) (bool, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CheckRollupsOperationAvailability")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, organizations.CheckRollupsOperationAvailabilityParams) (bool, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, organizations.CheckRollupsOperationAvailabilityParams) bool); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, organizations.CheckRollupsOperationAvailabilityParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrganizationsAPI_CheckRollupsOperationAvailability_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckRollupsOperationAvailability'
type IOrganizationsAPI_CheckRollupsOperationAvailability_Call struct {
	*mock.Call
}

// CheckRollupsOperationAvailability is a helper method to define mock.On call
//   - ctx context.Context
//   - params organizations.CheckRollupsOperationAvailabilityParams
func (_e *IOrganizationsAPI_Expecter) CheckRollupsOperationAvailability(ctx interface{}, params interface{}) *IOrganizationsAPI_CheckRollupsOperationAvailability_Call {
	return &IOrganizationsAPI_CheckRollupsOperationAvailability_Call{Call: _e.mock.On("CheckRollupsOperationAvailability", ctx, params)}
}

func (_c *IOrganizationsAPI_CheckRollupsOperationAvailability_Call) Run(run func(ctx context.Context, params organizations.CheckRollupsOperationAvailabilityParams)) *IOrganizationsAPI_CheckRollupsOperationAvailability_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(organizations.CheckRollupsOperationAvailabilityParams))
	})
	return _c
}

func (_c *IOrganizationsAPI_CheckRollupsOperationAvailability_Call) Return(_a0 bool, _a1 error) *IOrganizationsAPI_CheckRollupsOperationAvailability_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrganizationsAPI_CheckRollupsOperationAvailability_Call) RunAndReturn(run func(context.Context, organizations.CheckRollupsOperationAvailabilityParams) (bool, error)) *IOrganizationsAPI_CheckRollupsOperationAvailability_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields:
func (_m *IOrganizationsAPI) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IOrganizationsAPI_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type IOrganizationsAPI_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *IOrganizationsAPI_Expecter) Close() *IOrganizationsAPI_Close_Call {
	return &IOrganizationsAPI_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *IOrganizationsAPI_Close_Call) Run(run func()) *IOrganizationsAPI_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *IOrganizationsAPI_Close_Call) Return(_a0 error) *IOrganizationsAPI_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IOrganizationsAPI_Close_Call) RunAndReturn(run func() error) *IOrganizationsAPI_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrganization provides a mock function with given fields: ctx, params
func (_m *IOrganizationsAPI) CreateOrganization(ctx context.Context, params organizations.CreateOrganizationParams) (*models.Organization, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganization")
	}

	var r0 *models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, organizations.CreateOrganizationParams) (*models.Organization, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, organizations.CreateOrganizationParams) *models.Organization); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, organizations.CreateOrganizationParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrganizationsAPI_CreateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganization'
type IOrganizationsAPI_CreateOrganization_Call struct {
	*mock.Call
}

// CreateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - params organizations.CreateOrganizationParams
func (_e *IOrganizationsAPI_Expecter) CreateOrganization(ctx interface{}, params interface{}) *IOrganizationsAPI_CreateOrganization_Call {
	return &IOrganizationsAPI_CreateOrganization_Call{Call: _e.mock.On("CreateOrganization", ctx, params)}
}

func (_c *IOrganizationsAPI_CreateOrganization_Call) Run(run func(ctx context.Context, params organizations.CreateOrganizationParams)) *IOrganizationsAPI_CreateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(organizations.CreateOrganizationParams))
	})
	return _c
}

func (_c *IOrganizationsAPI_CreateOrganization_Call) Return(_a0 *models.Organization, _a1 error) *IOrganizationsAPI_CreateOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrganizationsAPI_CreateOrganization_Call) RunAndReturn(run func(context.Context, organizations.CreateOrganizationParams) (*models.Organization, error)) *IOrganizationsAPI_CreateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOrganization provides a mock function with given fields: ctx, organizationUUID
func (_m *IOrganizationsAPI) DeleteOrganization(ctx context.Context, organizationUUID uuid.UUID) error {
	ret := _m.Called(ctx, organizationUUID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, organizationUUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IOrganizationsAPI_DeleteOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOrganization'
type IOrganizationsAPI_DeleteOrganization_Call struct {
	*mock.Call
}

// DeleteOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationUUID uuid.UUID
func (_e *IOrganizationsAPI_Expecter) DeleteOrganization(ctx interface{}, organizationUUID interface{}) *IOrganizationsAPI_DeleteOrganization_Call {
	return &IOrganizationsAPI_DeleteOrganization_Call{Call: _e.mock.On("DeleteOrganization", ctx, organizationUUID)}
}

func (_c *IOrganizationsAPI_DeleteOrganization_Call) Run(run func(ctx context.Context, organizationUUID uuid.UUID)) *IOrganizationsAPI_DeleteOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *IOrganizationsAPI_DeleteOrganization_Call) Return(_a0 error) *IOrganizationsAPI_DeleteOrganization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IOrganizationsAPI_DeleteOrganization_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *IOrganizationsAPI_DeleteOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRollupsFromOrganization provides a mock function with given fields: ctx, params
func (_m *IOrganizationsAPI) DeleteRollupsFromOrganization(ctx context.Context, params organizations.DeleteRollupParams) (*models.Organization, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRollupsFromOrganization")
	}

	var r0 *models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, organizations.DeleteRollupParams) (*models.Organization, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, organizations.DeleteRollupParams) *models.Organization); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, organizations.DeleteRollupParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrganizationsAPI_DeleteRollupsFromOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRollupsFromOrganization'
type IOrganizationsAPI_DeleteRollupsFromOrganization_Call struct {
	*mock.Call
}

// DeleteRollupsFromOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - params organizations.DeleteRollupParams
func (_e *IOrganizationsAPI_Expecter) DeleteRollupsFromOrganization(ctx interface{}, params interface{}) *IOrganizationsAPI_DeleteRollupsFromOrganization_Call {
	return &IOrganizationsAPI_DeleteRollupsFromOrganization_Call{Call: _e.mock.On("DeleteRollupsFromOrganization", ctx, params)}
}

func (_c *IOrganizationsAPI_DeleteRollupsFromOrganization_Call) Run(run func(ctx context.Context, params organizations.DeleteRollupParams)) *IOrganizationsAPI_DeleteRollupsFromOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(organizations.DeleteRollupParams))
	})
	return _c
}

func (_c *IOrganizationsAPI_DeleteRollupsFromOrganization_Call) Return(_a0 *models.Organization, _a1 error) *IOrganizationsAPI_DeleteRollupsFromOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrganizationsAPI_DeleteRollupsFromOrganization_Call) RunAndReturn(run func(context.Context, organizations.DeleteRollupParams) (*models.Organization, error)) *IOrganizationsAPI_DeleteRollupsFromOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganization provides a mock function with given fields: ctx, organizationUUID
func (_m *IOrganizationsAPI) GetOrganization(ctx context.Context, organizationUUID uuid.UUID) (*models.Organization, error) {
	ret := _m.Called(ctx, organizationUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganization")
	}

	var r0 *models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Organization, error)); ok {
		return rf(ctx, organizationUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Organization); ok {
		r0 = rf(ctx, organizationUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, organizationUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrganizationsAPI_GetOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganization'
type IOrganizationsAPI_GetOrganization_Call struct {
	*mock.Call
}

// GetOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - organizationUUID uuid.UUID
func (_e *IOrganizationsAPI_Expecter) GetOrganization(ctx interface{}, organizationUUID interface{}) *IOrganizationsAPI_GetOrganization_Call {
	return &IOrganizationsAPI_GetOrganization_Call{Call: _e.mock.On("GetOrganization", ctx, organizationUUID)}
}

func (_c *IOrganizationsAPI_GetOrganization_Call) Run(run func(ctx context.Context, organizationUUID uuid.UUID)) *IOrganizationsAPI_GetOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *IOrganizationsAPI_GetOrganization_Call) Return(_a0 *models.Organization, _a1 error) *IOrganizationsAPI_GetOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrganizationsAPI_GetOrganization_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*models.Organization, error)) *IOrganizationsAPI_GetOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// ListOrganizations provides a mock function with given fields: ctx, opts
func (_m *IOrganizationsAPI) ListOrganizations(ctx context.Context, opts *organizations.AllOrganizationsOpts) ([]*models.Organization, *bool, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for ListOrganizations")
	}

	var r0 []*models.Organization
	var r1 *bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *organizations.AllOrganizationsOpts) ([]*models.Organization, *bool, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *organizations.AllOrganizationsOpts) []*models.Organization); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *organizations.AllOrganizationsOpts) *bool); ok {
		r1 = rf(ctx, opts)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bool)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *organizations.AllOrganizationsOpts) error); ok {
		r2 = rf(ctx, opts)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IOrganizationsAPI_ListOrganizations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListOrganizations'
type IOrganizationsAPI_ListOrganizations_Call struct {
	*mock.Call
}

// ListOrganizations is a helper method to define mock.On call
//   - ctx context.Context
//   - opts *organizations.AllOrganizationsOpts
func (_e *IOrganizationsAPI_Expecter) ListOrganizations(ctx interface{}, opts interface{}) *IOrganizationsAPI_ListOrganizations_Call {
	return &IOrganizationsAPI_ListOrganizations_Call{Call: _e.mock.On("ListOrganizations", ctx, opts)}
}

func (_c *IOrganizationsAPI_ListOrganizations_Call) Run(run func(ctx context.Context, opts *organizations.AllOrganizationsOpts)) *IOrganizationsAPI_ListOrganizations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*organizations.AllOrganizationsOpts))
	})
	return _c
}

func (_c *IOrganizationsAPI_ListOrganizations_Call) Return(_a0 []*models.Organization, _a1 *bool, _a2 error) *IOrganizationsAPI_ListOrganizations_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *IOrganizationsAPI_ListOrganizations_Call) RunAndReturn(run func(context.Context, *organizations.AllOrganizationsOpts) ([]*models.Organization, *bool, error)) *IOrganizationsAPI_ListOrganizations_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveUserFromOrganization provides a mock function with given fields: ctx, params
func (_m *IOrganizationsAPI) RemoveUserFromOrganization(ctx context.Context, params organizations.RemoveUserParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RemoveUserFromOrganization")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, organizations.RemoveUserParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IOrganizationsAPI_RemoveUserFromOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveUserFromOrganization'
type IOrganizationsAPI_RemoveUserFromOrganization_Call struct {
	*mock.Call
}

// RemoveUserFromOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - params organizations.RemoveUserParams
func (_e *IOrganizationsAPI_Expecter) RemoveUserFromOrganization(ctx interface{}, params interface{}) *IOrganizationsAPI_RemoveUserFromOrganization_Call {
	return &IOrganizationsAPI_RemoveUserFromOrganization_Call{Call: _e.mock.On("RemoveUserFromOrganization", ctx, params)}
}

func (_c *IOrganizationsAPI_RemoveUserFromOrganization_Call) Run(run func(ctx context.Context, params organizations.RemoveUserParams)) *IOrganizationsAPI_RemoveUserFromOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(organizations.RemoveUserParams))
	})
	return _c
}

func (_c *IOrganizationsAPI_RemoveUserFromOrganization_Call) Return(_a0 error) *IOrganizationsAPI_RemoveUserFromOrganization_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IOrganizationsAPI_RemoveUserFromOrganization_Call) RunAndReturn(run func(context.Context, organizations.RemoveUserParams) error) *IOrganizationsAPI_RemoveUserFromOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// TransferRollupsToOrganization provides a mock function with given fields: ctx, params
func (_m *IOrganizationsAPI) TransferRollupsToOrganization(ctx context.Context, params organizations.TransferRollupsParams) (*models.Organization, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for TransferRollupsToOrganization")
	}

	var r0 *models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, organizations.TransferRollupsParams) (*models.Organization, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, organizations.TransferRollupsParams) *models.Organization); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, organizations.TransferRollupsParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrganizationsAPI_TransferRollupsToOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferRollupsToOrganization'
type IOrganizationsAPI_TransferRollupsToOrganization_Call struct {
	*mock.Call
}

// TransferRollupsToOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - params organizations.TransferRollupsParams
func (_e *IOrganizationsAPI_Expecter) TransferRollupsToOrganization(ctx interface{}, params interface{}) *IOrganizationsAPI_TransferRollupsToOrganization_Call {
	return &IOrganizationsAPI_TransferRollupsToOrganization_Call{Call: _e.mock.On("TransferRollupsToOrganization", ctx, params)}
}

func (_c *IOrganizationsAPI_TransferRollupsToOrganization_Call) Run(run func(ctx context.Context, params organizations.TransferRollupsParams)) *IOrganizationsAPI_TransferRollupsToOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(organizations.TransferRollupsParams))
	})
	return _c
}

func (_c *IOrganizationsAPI_TransferRollupsToOrganization_Call) Return(_a0 *models.Organization, _a1 error) *IOrganizationsAPI_TransferRollupsToOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrganizationsAPI_TransferRollupsToOrganization_Call) RunAndReturn(run func(context.Context, organizations.TransferRollupsParams) (*models.Organization, error)) *IOrganizationsAPI_TransferRollupsToOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrganization provides a mock function with given fields: ctx, params
func (_m *IOrganizationsAPI) UpdateOrganization(ctx context.Context, params organizations.UpdateOrganizationParams) (*models.Organization, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrganization")
	}

	var r0 *models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, organizations.UpdateOrganizationParams) (*models.Organization, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, organizations.UpdateOrganizationParams) *models.Organization); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, organizations.UpdateOrganizationParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrganizationsAPI_UpdateOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrganization'
type IOrganizationsAPI_UpdateOrganization_Call struct {
	*mock.Call
}

// UpdateOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - params organizations.UpdateOrganizationParams
func (_e *IOrganizationsAPI_Expecter) UpdateOrganization(ctx interface{}, params interface{}) *IOrganizationsAPI_UpdateOrganization_Call {
	return &IOrganizationsAPI_UpdateOrganization_Call{Call: _e.mock.On("UpdateOrganization", ctx, params)}
}

func (_c *IOrganizationsAPI_UpdateOrganization_Call) Run(run func(ctx context.Context, params organizations.UpdateOrganizationParams)) *IOrganizationsAPI_UpdateOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(organizations.UpdateOrganizationParams))
	})
	return _c
}

func (_c *IOrganizationsAPI_UpdateOrganization_Call) Return(_a0 *models.Organization, _a1 error) *IOrganizationsAPI_UpdateOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrganizationsAPI_UpdateOrganization_Call) RunAndReturn(run func(context.Context, organizations.UpdateOrganizationParams) (*models.Organization, error)) *IOrganizationsAPI_UpdateOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserRoleInOrganization provides a mock function with given fields: ctx, params
func (_m *IOrganizationsAPI) UpdateUserRoleInOrganization(ctx context.Context, params organizations.UpdateUserRoleParams) (*models.Organization, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserRoleInOrganization")
	}

	var r0 *models.Organization
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, organizations.UpdateUserRoleParams) (*models.Organization, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, organizations.UpdateUserRoleParams) *models.Organization); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Organization)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, organizations.UpdateUserRoleParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IOrganizationsAPI_UpdateUserRoleInOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserRoleInOrganization'
type IOrganizationsAPI_UpdateUserRoleInOrganization_Call struct {
	*mock.Call
}

// UpdateUserRoleInOrganization is a helper method to define mock.On call
//   - ctx context.Context
//   - params organizations.UpdateUserRoleParams
func (_e *IOrganizationsAPI_Expecter) UpdateUserRoleInOrganization(ctx interface{}, params interface{}) *IOrganizationsAPI_UpdateUserRoleInOrganization_Call {
	return &IOrganizationsAPI_UpdateUserRoleInOrganization_Call{Call: _e.mock.On("UpdateUserRoleInOrganization", ctx, params)}
}

func (_c *IOrganizationsAPI_UpdateUserRoleInOrganization_Call) Run(run func(ctx context.Context, params organizations.UpdateUserRoleParams)) *IOrganizationsAPI_UpdateUserRoleInOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(organizations.UpdateUserRoleParams))
	})
	return _c
}

func (_c *IOrganizationsAPI_UpdateUserRoleInOrganization_Call) Return(_a0 *models.Organization, _a1 error) *IOrganizationsAPI_UpdateUserRoleInOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *IOrganizationsAPI_UpdateUserRoleInOrganization_Call) RunAndReturn(run func(context.Context, organizations.UpdateUserRoleParams) (*models.Organization, error)) *IOrganizationsAPI_UpdateUserRoleInOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// NewIOrganizationsAPI creates a new instance of IOrganizationsAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOrganizationsAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOrganizationsAPI {
	mock := &IOrganizationsAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
