// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	models "gateguard/internal/models"

	mock "github.com/stretchr/testify/mock"

	repository "gateguard/internal/repository"
)

// IRepository is an autogenerated mock type for the IRepository type
type IRepository struct {
	mock.Mock
}

type IRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *IRepository) EXPECT() *IRepository_Expecter {
	return &IRepository_Expecter{mock: &_m.Mock}
}

// AllInvitations provides a mock function with given fields: ctx, filter, options
func (_m *IRepository) AllInvitations(ctx context.Context, filter *repository.AllInvitationsFilter, options ...repository.QueryOption) ([]*models.Invitation, bool, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, filter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AllInvitations")
	}

	var r0 []*models.Invitation
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *repository.AllInvitationsFilter, ...repository.QueryOption) ([]*models.Invitation, bool, error)); ok {
		return rf(ctx, filter, options...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *repository.AllInvitationsFilter, ...repository.QueryOption) []*models.Invitation); ok {
		r0 = rf(ctx, filter, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Invitation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *repository.AllInvitationsFilter, ...repository.QueryOption) bool); ok {
		r1 = rf(ctx, filter, options...)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *repository.AllInvitationsFilter, ...repository.QueryOption) error); ok {
		r2 = rf(ctx, filter, options...)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// IRepository_AllInvitations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllInvitations'
type IRepository_AllInvitations_Call struct {
	*mock.Call
}

// AllInvitations is a helper method to define mock.On call
//   - ctx context.Context
//   - filter *repository.AllInvitationsFilter
//   - options ...repository.QueryOption
func (_e *IRepository_Expecter) AllInvitations(ctx interface{}, filter interface{}, options ...interface{}) *IRepository_AllInvitations_Call {
	return &IRepository_AllInvitations_Call{Call: _e.mock.On("AllInvitations",
		append([]interface{}{ctx, filter}, options...)...)}
}

func (_c *IRepository_AllInvitations_Call) Run(run func(ctx context.Context, filter *repository.AllInvitationsFilter, options ...repository.QueryOption)) *IRepository_AllInvitations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]repository.QueryOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(repository.QueryOption)
			}
		}
		run(args[0].(context.Context), args[1].(*repository.AllInvitationsFilter), variadicArgs...)
	})
	return _c
}

func (_c *IRepository_AllInvitations_Call) Return(invitations []*models.Invitation, hasMore bool, err error) *IRepository_AllInvitations_Call {
	_c.Call.Return(invitations, hasMore, err)
	return _c
}

func (_c *IRepository_AllInvitations_Call) RunAndReturn(run func(context.Context, *repository.AllInvitationsFilter, ...repository.QueryOption) ([]*models.Invitation, bool, error)) *IRepository_AllInvitations_Call {
	_c.Call.Return(run)
	return _c
}

// AllUsers provides a mock function with given fields: ctx
func (_m *IRepository) AllUsers(ctx context.Context) ([]*models.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllUsers")
	}

	var r0 []*models.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// IRepository_AllUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllUsers'
type IRepository_AllUsers_Call struct {
	*mock.Call
}

// AllUsers is a helper method to define mock.On call
//   - ctx context.Context
func (_e *IRepository_Expecter) AllUsers(ctx interface{}) *IRepository_AllUsers_Call {
	return &IRepository_AllUsers_Call{Call: _e.mock.On("AllUsers", ctx)}
}

func (_c *IRepository_AllUsers_Call) Run(run func(ctx context.Context)) *IRepository_AllUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *IRepository_AllUsers_Call) Return(users []*models.User, err error) *IRepository_AllUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *IRepository_AllUsers_Call) RunAndReturn(run func(context.Context) ([]*models.User, error)) *IRepository_AllUsers_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvitation provides a mock function with given fields: ctx, model
func (_m *IRepository) CreateInvitation(ctx context.Context, model *models.Invitation) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Invitation) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRepository_CreateInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvitation'
type IRepository_CreateInvitation_Call struct {
	*mock.Call
}

// CreateInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - model *models.Invitation
func (_e *IRepository_Expecter) CreateInvitation(ctx interface{}, model interface{}) *IRepository_CreateInvitation_Call {
	return &IRepository_CreateInvitation_Call{Call: _e.mock.On("CreateInvitation", ctx, model)}
}

func (_c *IRepository_CreateInvitation_Call) Run(run func(ctx context.Context, model *models.Invitation)) *IRepository_CreateInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Invitation))
	})
	return _c
}

func (_c *IRepository_CreateInvitation_Call) Return(_a0 error) *IRepository_CreateInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRepository_CreateInvitation_Call) RunAndReturn(run func(context.Context, *models.Invitation) error) *IRepository_CreateInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, model
func (_m *IRepository) CreateUser(ctx context.Context, model *models.User) error {
	ret := _m.Called(ctx, model)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User) error); ok {
		r0 = rf(ctx, model)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRepository_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type IRepository_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - model *models.User
func (_e *IRepository_Expecter) CreateUser(ctx interface{}, model interface{}) *IRepository_CreateUser_Call {
	return &IRepository_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, model)}
}

func (_c *IRepository_CreateUser_Call) Run(run func(ctx context.Context, model *models.User)) *IRepository_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User))
	})
	return _c
}

func (_c *IRepository_CreateUser_Call) Return(_a0 error) *IRepository_CreateUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRepository_CreateUser_Call) RunAndReturn(run func(context.Context, *models.User) error) *IRepository_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetInvitation provides a mock function with given fields: ctx, model, getter
func (_m *IRepository) GetInvitation(ctx context.Context, model *models.Invitation, getter repository.InvitationGetter) error {
	ret := _m.Called(ctx, model, getter)

	if len(ret) == 0 {
		panic("no return value specified for GetInvitation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Invitation, repository.InvitationGetter) error); ok {
		r0 = rf(ctx, model, getter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRepository_GetInvitation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetInvitation'
type IRepository_GetInvitation_Call struct {
	*mock.Call
}

// GetInvitation is a helper method to define mock.On call
//   - ctx context.Context
//   - model *models.Invitation
//   - getter repository.InvitationGetter
func (_e *IRepository_Expecter) GetInvitation(ctx interface{}, model interface{}, getter interface{}) *IRepository_GetInvitation_Call {
	return &IRepository_GetInvitation_Call{Call: _e.mock.On("GetInvitation", ctx, model, getter)}
}

func (_c *IRepository_GetInvitation_Call) Run(run func(ctx context.Context, model *models.Invitation, getter repository.InvitationGetter)) *IRepository_GetInvitation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Invitation), args[2].(repository.InvitationGetter))
	})
	return _c
}

func (_c *IRepository_GetInvitation_Call) Return(_a0 error) *IRepository_GetInvitation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRepository_GetInvitation_Call) RunAndReturn(run func(context.Context, *models.Invitation, repository.InvitationGetter) error) *IRepository_GetInvitation_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function with given fields: ctx, model, getter
func (_m *IRepository) GetUser(ctx context.Context, model *models.User, getter repository.UserGetter) error {
	ret := _m.Called(ctx, model, getter)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User, repository.UserGetter) error); ok {
		r0 = rf(ctx, model, getter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type IRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - model *models.User
//   - getter repository.UserGetter
func (_e *IRepository_Expecter) GetUser(ctx interface{}, model interface{}, getter interface{}) *IRepository_GetUser_Call {
	return &IRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, model, getter)}
}

func (_c *IRepository_GetUser_Call) Run(run func(ctx context.Context, model *models.User, getter repository.UserGetter)) *IRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.User), args[2].(repository.UserGetter))
	})
	return _c
}

func (_c *IRepository_GetUser_Call) Return(_a0 error) *IRepository_GetUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRepository_GetUser_Call) RunAndReturn(run func(context.Context, *models.User, repository.UserGetter) error) *IRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateInvitationBy provides a mock function with given fields: ctx, model, getter, columns
func (_m *IRepository) UpdateInvitationBy(ctx context.Context, model *models.Invitation, getter repository.InvitationGetter, columns ...string) error {
	_va := make([]interface{}, len(columns))
	for _i := range columns {
		_va[_i] = columns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, model, getter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateInvitationBy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Invitation, repository.InvitationGetter, ...string) error); ok {
		r0 = rf(ctx, model, getter, columns...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRepository_UpdateInvitationBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateInvitationBy'
type IRepository_UpdateInvitationBy_Call struct {
	*mock.Call
}

// UpdateInvitationBy is a helper method to define mock.On call
//   - ctx context.Context
//   - model *models.Invitation
//   - getter repository.InvitationGetter
//   - columns ...string
func (_e *IRepository_Expecter) UpdateInvitationBy(ctx interface{}, model interface{}, getter interface{}, columns ...interface{}) *IRepository_UpdateInvitationBy_Call {
	return &IRepository_UpdateInvitationBy_Call{Call: _e.mock.On("UpdateInvitationBy",
		append([]interface{}{ctx, model, getter}, columns...)...)}
}

func (_c *IRepository_UpdateInvitationBy_Call) Run(run func(ctx context.Context, model *models.Invitation, getter repository.InvitationGetter, columns ...string)) *IRepository_UpdateInvitationBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(*models.Invitation), args[2].(repository.InvitationGetter), variadicArgs...)
	})
	return _c
}

func (_c *IRepository_UpdateInvitationBy_Call) Return(_a0 error) *IRepository_UpdateInvitationBy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRepository_UpdateInvitationBy_Call) RunAndReturn(run func(context.Context, *models.Invitation, repository.InvitationGetter, ...string) error) *IRepository_UpdateInvitationBy_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserBy provides a mock function with given fields: ctx, model, getter, columns
func (_m *IRepository) UpdateUserBy(ctx context.Context, model *models.User, getter repository.UserGetter, columns ...string) error {
	_va := make([]interface{}, len(columns))
	for _i := range columns {
		_va[_i] = columns[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, model, getter)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserBy")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.User, repository.UserGetter, ...string) error); ok {
		r0 = rf(ctx, model, getter, columns...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IRepository_UpdateUserBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserBy'
type IRepository_UpdateUserBy_Call struct {
	*mock.Call
}

// UpdateUserBy is a helper method to define mock.On call
//   - ctx context.Context
//   - model *models.User
//   - getter repository.UserGetter
//   - columns ...string
func (_e *IRepository_Expecter) UpdateUserBy(ctx interface{}, model interface{}, getter interface{}, columns ...interface{}) *IRepository_UpdateUserBy_Call {
	return &IRepository_UpdateUserBy_Call{Call: _e.mock.On("UpdateUserBy",
		append([]interface{}{ctx, model, getter}, columns...)...)}
}

func (_c *IRepository_UpdateUserBy_Call) Run(run func(ctx context.Context, model *models.User, getter repository.UserGetter, columns ...string)) *IRepository_UpdateUserBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(*models.User), args[2].(repository.UserGetter), variadicArgs...)
	})
	return _c
}

func (_c *IRepository_UpdateUserBy_Call) Return(_a0 error) *IRepository_UpdateUserBy_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *IRepository_UpdateUserBy_Call) RunAndReturn(run func(context.Context, *models.User, repository.UserGetter, ...string) error) *IRepository_UpdateUserBy_Call {
	_c.Call.Return(run)
	return _c
}

// NewIRepository creates a new instance of IRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IRepository {
	mock := &IRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
